import Link from "next/link";
import { notFound } from "next/navigation";
import { requireTrainingAdmin } from "@/lib/admin-auth";
import { getAdminAircraft,getOpenStaleFlags } from "@/lib/content-admin-repository";
import { trainingContentDomains } from "@/lib/content-admin-types";
import { addVariantAction,createAiDraftAction,createDraftAction,createReferenceAction,publishAircraftAction,registerRevisionAction,resolveStaleAction } from "../../actions";

export const dynamic="force-dynamic";
const Hidden=({aircraftId}:{aircraftId:string})=><input type="hidden" name="aircraftId" value={aircraftId}/>;

export default async function AdminAircraftPage({params}:Readonly<{params:Promise<{aircraftId:string}>}>){
  await requireTrainingAdmin();const {aircraftId}=await params;const [aircraft,stale]=await Promise.all([getAdminAircraft(aircraftId),getOpenStaleFlags(aircraftId)]);if(!aircraft)notFound();
  return <main className="shell aircraft-detail"><Link className="back-link" href="/admin">← Content administration</Link>
    <section className="workspace-section-hero"><p className="eyebrow">{aircraft.status} · {aircraft.manufacturer}</p><h1>{aircraft.displayName}</h1><p className="lede">{aircraft.variants.join(" · ")||"No variants"} · {aircraft.manualRevisionCount} manual revisions · {stale.length} open stale reviews</p>{aircraft.status!=="published"?<form action={publishAircraftAction}><Hidden aircraftId={aircraftId}/><button type="submit">Publish aircraft catalogue entry</button></form>:null}</section>
    <section className="reference-library"><h2>Variants</h2><form action={addVariantAction}><Hidden aircraftId={aircraftId}/><input name="variant" placeholder="Variant" required/> <button type="submit">Add variant</button></form></section>
    <section className="reference-library"><h2>Register immutable manual revision</h2><form action={registerRevisionAction}><Hidden aircraftId={aircraftId}/><p><input name="manualId" placeholder="Manual family ID" required/> <input name="revisionId" placeholder="Revision ID" required/> <input name="revision" placeholder="Revision code" required/></p><p><input name="title" placeholder="Manual title" required/> <input name="publisher" placeholder="Publisher" required/> <input name="sourceKind" placeholder="AFM / POH / FCOM / QRH / TRAINING_MANUAL" required/> <input name="issueDate" placeholder="Issue date" required/></p><p><input name="sourceUri" placeholder="Source URI / storage key"/> <input name="checksum" placeholder="SHA-256 checksum"/> <input name="authorityNote" placeholder="Authority note"/></p><button type="submit">Register revision</button></form><ol className="chapter-list">{aircraft.manuals.map(m=><li key={m.revisionId}><span className="chapter-number">{m.revision}</span><div><strong>{m.title}</strong><span>{m.publisher} · {m.revisionId}{m.sourceUri?` · ${m.sourceUri}`:""}</span></div></li>)}</ol></section>
    <section className="reference-library"><h2>Source references</h2><form action={createReferenceAction}><Hidden aircraftId={aircraftId}/><p><input name="revisionId" placeholder="Revision ID" required/> <input name="chapter" placeholder="Chapter"/> <input name="section" placeholder="Section"/> <input name="pageLabel" placeholder="Page" required/> <input name="note" placeholder="Note"/> <button type="submit">Add reference</button></p></form><ol className="chapter-list">{aircraft.sourceReferences.map(r=><li key={r.id}><span className="chapter-number">SRC</span><div><strong>{r.chapter||"Source"} · p. {r.pageLabel}</strong><span>{r.section||""} · {r.id}</span></div></li>)}</ol></section>

    <section className="reference-library"><p className="eyebrow">AI-assisted authoring</p><h2>Generate a governed draft from source material</h2><p>The model receives only the selected reference metadata and the source excerpt below. Its result is saved as <strong>ai-assisted / draft</strong>; it cannot approve or publish itself. Use the review screen to inspect every claim and edit it into a new immutable human version.</p><form action={createAiDraftAction}><Hidden aircraftId={aircraftId}/><p><select name="domain">{trainingContentDomains.map(domain=><option key={domain}>{domain}</option>)}</select> <input name="contentKey" defaultValue="bundle"/> <input name="sourceReferenceIds" placeholder="Source reference IDs, comma-separated" required style={{width:"45%"}}/></p><p><input name="goal" placeholder="Drafting goal, e.g. Build the hydraulic system lesson from this excerpt" required style={{width:"100%"}}/></p><textarea name="sourceText" placeholder="Paste the controlled source excerpt here. Do not paste unrelated instructions." required rows={14} style={{width:"100%"}}/><p><button type="submit">Generate governed AI draft</button></p></form></section>

    <section className="reference-library"><h2>Create governed JSON draft manually</h2><p>Drafts must retain aircraft-owned source references. Approval and publication additionally require a valid product-domain payload.</p><form action={createDraftAction}><Hidden aircraftId={aircraftId}/><p><select name="domain">{trainingContentDomains.map(domain=><option key={domain}>{domain}</option>)}</select> <input name="contentKey" defaultValue="bundle"/> <select name="origin"><option value="human">human</option><option value="import">import</option></select></p><p><input name="sourceReferenceIds" placeholder="Source reference IDs, comma-separated" required style={{width:"100%"}}/></p><textarea name="payload" placeholder='{"aircraftId":"..."}' required rows={12} style={{width:"100%"}}/><p><button type="submit">Create draft version</button></p></form></section>
    <section className="reference-library"><h2>Content versions</h2><ol className="chapter-list">{aircraft.contentVersions.map(v=><li key={v.id}><span className="chapter-number">v{v.versionNo}</span><div><strong>{v.domain}/{v.contentKey} · {v.state}</strong><span>{v.origin} · {v.id}</span><Link href={`/admin/aircraft/${aircraftId}/content/${v.id}`}>Review / edit →</Link></div></li>)}</ol></section>
    {stale.length?<section className="reference-library"><h2>Stale-content review</h2><ol className="chapter-list">{stale.map(flag=><li key={String(flag.stale_id)}><span className="chapter-number">!</span><div><strong>{flag.domain}/{flag.content_key}</strong><span>{flag.reason} · newer revision {flag.newer_revision_id}</span><form action={resolveStaleAction}><Hidden aircraftId={aircraftId}/><input type="hidden" name="staleId" value={String(flag.stale_id)}/><input name="note" placeholder="Resolution / replacement note" required/><button type="submit">Resolve review</button></form></div></li>)}</ol></section>:null}
  </main>;
}
