import type { AircraftKnowledgeContent, TrainingSourceReference } from "./universal-aircraft-content.ts";

const AIRCRAFT_ID = "learjet-35-36";
const FSI_MANUAL_ID = "fsi-learjet-35-36-ptm-r1-1";

const source = (chapter: number, section: string, pageLabel: string): TrainingSourceReference => ({
  manualId: FSI_MANUAL_ID,
  chapter: String(chapter),
  section,
  pageLabel,
});

export const learjet3536NativeKnowledge: AircraftKnowledgeContent = {
  aircraftId: AIRCRAFT_ID,
  title: "Learjet 35/36 Knowledge Training",
  sourceNote: "Native M9 question bank migrated from the existing FlightSafety-backed Learjet training content.",
  disclaimer: "Training/familiarization content only. Applicable AFM, approved supplements, operator SOPs, QRH and regulatory publications remain controlling.",
  questions: [
    {
      id: "q-generator-capacity",
      area: "Electrical",
      prompt: "After one generator fails in flight, what is the key electrical-system mental model?",
      choices: ["Both generators are required for any DC power", "One generator can sustain the normal DC load", "Only the emergency battery remains", "The inverters become DC generators"],
      correctIndex: 1,
      explanation: "Each engine-driven generator is rated 30 V / 400 A and the training source states that one generator can sustain the normal DC load.",
      sources: [source(2, "Electrical Power Systems — Introduction", "2-1")],
    },
    {
      id: "q-hydraulic-pressure",
      area: "Hydraulics",
      prompt: "What main hydraulic pressure should you have in mind as the normal Learjet training reference?",
      choices: ["About 550 psi", "About 1,000 psi", "About 1,550 psi", "About 3,000 psi"],
      correctIndex: 2,
      explanation: "The source-backed training reference is approximately 1,550 psi.",
      sources: [source(13, "Hydraulic Power System — General", "13-1")],
    },
    {
      id: "q-primary-controls",
      area: "Flight controls",
      prompt: "How are the primary aileron, elevator and rudder controls actuated?",
      choices: ["Hydraulically boosted", "Electrically signaled", "Mechanically, without hydraulic/electric boost", "Pneumatically"],
      correctIndex: 2,
      explanation: "Primary flight controls are mechanical. Hydraulics are used by secondary systems such as flaps and spoilers/spoilerons.",
      sources: [source(15, "Flight Controls — General", "15-1")],
    },
    {
      id: "q-fuel-mental-model",
      area: "Fuel",
      prompt: "Which fuel-system mental model is most useful for the Learjet 35/36?",
      choices: ["Engines feed directly from every tank equally", "Wing-fed engines with tip/fuselage transfer management", "Fuselage tank feeds engines directly at all times", "Only tip tanks feed the engines"],
      correctIndex: 1,
      explanation: "The engines are supplied from the wing system while tip/fuselage fuel is managed through transfer logic.",
      sources: [source(5, "Fuel Tanks and Tank Venting — General", "5-3")],
    },
    {
      id: "q-wing-fuel",
      area: "Fuel",
      prompt: "What wing-fuel minimum does the training source specify for takeoff or an intentional go-around?",
      choices: ["300 lb", "600 lb", "1,000 lb", "No minimum"],
      correctIndex: 1,
      explanation: "The registered training source specifies at least 600 lb in the wings for takeoff or an intentional go-around.",
      sources: [source(5, "Fuel Tanks and Tank Venting — General", "5-3")],
    },
    {
      id: "q-press-mode",
      area: "Pressurization",
      prompt: "What is the normal pressurization mode in the training flow?",
      choices: ["MAN", "AUTO", "OFF", "EMER only"],
      correctIndex: 1,
      explanation: "Normal pressurization setup uses AUTO with expected cruise altitude and a suitable cabin rate selected.",
      sources: [source(12, "Normal System Operation — Before Takeoff", "12-8")],
    },
    {
      id: "q-start-monitor",
      area: "Powerplant",
      prompt: "Which indications are central to monitoring an engine start?",
      choices: ["Hydraulic pressure and cabin rate", "N2 and ITT, with N1 as a primary engine indication", "Only N1", "Fuel quantity only"],
      correctIndex: 1,
      explanation: "N2 and ITT are central during the start; N1 is the third primary engine indication.",
      sources: [source(7, "Engine Instrumentation", "7-21")],
    },
    {
      id: "q-starter-release",
      area: "Powerplant",
      prompt: "Why does FlyTally show the starter-release value as 45% or 50% N2 rather than one exact number?",
      choices: ["The value is random", "It depends on fuel-computer/configuration", "It depends only on outside temperature", "The manual gives no information"],
      correctIndex: 1,
      explanation: "The applicable automatic release threshold differs with configuration; FlyTally preserves that distinction instead of flattening it.",
      sources: [source(7, "Other Start Functions", "7-20")],
    },
    {
      id: "q-air-ignition",
      area: "Powerplant",
      prompt: "When is selective air ignition used in the normal training flow?",
      choices: ["Only during cruise", "Takeoff and landing", "Only after shutdown", "Never"],
      correctIndex: 1,
      explanation: "The source-backed normal flow uses L and R AIR IGN ON for takeoff and landing.",
      sources: [source(7, "Ignition — Selective Mode", "7-14")],
    },
    {
      id: "q-vspeeds",
      area: "Performance",
      prompt: "How should V1, VR and V2 be handled in Quick Reference?",
      choices: ["Use one fixed Learjet value", "Calculate/set them from current performance data", "Ignore them in simulation", "Always use 150 kt"],
      correctIndex: 1,
      explanation: "V-speeds are performance-derived for the actual condition. FlyTally deliberately does not publish a false universal value.",
      sources: [source(18, "Takeoff Setup / Standard Callouts", "18-8–18-9")],
    },
  ],
};
