import {
  learjet3536NativeLimitations,
  learjet3536NativePerformance,
} from "./learjet-native-content.ts";
import type {
  AircraftLimitationsContent,
  AircraftPerformanceContent,
  PerformanceDataset,
  TrainingSourceReference,
} from "./universal-aircraft-content.ts";

const FSI = "fsi-learjet-35-36-ptm-r1-1";
const CAE = "cae-simuflite-learjet-35-36-crh-feb-2007";
const JAYDEE = "jaydee-learjet-35a-checklist-v1-35-wip1";
const FLYSIMWARE = "flysimware-learjet-35a-msfs-v1-2";

const fsi = (chapter: number, section: string, pageLabel: string): TrainingSourceReference => ({
  manualId: FSI,
  chapter: String(chapter),
  section,
  pageLabel,
});
const cae = (section: string, pageLabel: string): TrainingSourceReference => ({
  manualId: CAE,
  section,
  pageLabel,
});
const jaydee = (section: string, pageLabel = "1"): TrainingSourceReference => ({
  manualId: JAYDEE,
  section,
  pageLabel,
  note: "Simulator workflow reference; the source explicitly states that some procedures differ from real-world procedures.",
});
const flysimware = (section: string, pageLabel: string): TrainingSourceReference => ({
  manualId: FLYSIMWARE,
  section,
  pageLabel,
  note: "Flysimware implementation reference only.",
});

const commonBoundary =
  "Training/familiarization data only. CAE and FlightSafety are training references, not substitutes for the applicable AFM/approved supplements/operator documentation. JayDee and Flysimware data remain explicitly supplementary. Configuration-dependent values are not silently flattened into one universal Learjet value.";

const takeoffSpeedRows = [
  [13000, 8, 125, 125], [13000, 20, 125, 125],
  [14000, 8, 125, 128], [14000, 20, 125, 125],
  [15000, 8, 130, 133], [15000, 20, 127, 127],
  [16000, 8, 134, 137], [16000, 20, 130, 130],
  [17000, 8, 138, 141], [17000, 20, 133, 133],
  [18000, 8, 142, 145], [18000, 20, 136, 136],
] as const;

const maxContinuousRows = [
  [0, 15, 94.8, "+0.9", "-0.9"],
  [5000, 5, 96.5, "+0.9", "-0.6"],
  [10000, -5, 97.8, "+0.6", "-0.6"],
  [15000, -15, 98.1, "+0.3", "-0.3"],
  [20000, -25, 98.2, "+0.3", "-0.3"],
  [25000, -35, 99.3, "+0.3", "-0.3"],
  [30000, -40, 99.6, "—", "-0.6"],
  [35000, -40, 99.3, "—", "-0.6"],
  [40000, -40, 98.1, "—", "-0.5"],
  [45000, -40, 96.4, "—", "-0.4"],
] as const;

const vrefRows = [
  [10000, 105], [11000, 110], [12000, 115], [13000, 120], [14000, 124],
  [15000, 128], [16000, 132], [17000, 135], [18000, 138],
] as const;

const pilotDatasets: readonly PerformanceDataset[] = [
  {
    id: "fsi-takeoff-planning-sequence",
    title: "Takeoff performance — required planning sequence",
    description: "FlightSafety Chapter 20 defines the takeoff limit as the most restrictive certified, climb/brake-energy, runway-distance and obstacle-clearance result. The source uses AFM charts/nomograms; FlyTally does not invent a substitute equation.",
    kind: "reference-table",
    axes: [{ key: "step", label: "Planning check", values: ["1 Certified weight", "2 Climb / brake energy", "3 Runway distance", "4 Obstacle clearance"] }],
    outputs: [{ key: "requirement", label: "Requirement" }],
    rows: [
      { inputs: { step: "1 Certified weight" }, outputs: { requirement: "Do not exceed the applicable configuration's maximum certified takeoff weight." } },
      { inputs: { step: "2 Climb / brake energy" }, outputs: { requirement: "Use the applicable Takeoff Weight Limits chart for pressure altitude and temperature." } },
      { inputs: { step: "3 Runway distance" }, outputs: { requirement: "Use the applicable Takeoff Distance chart for runway and ambient conditions." } },
      { inputs: { step: "4 Obstacle clearance" }, outputs: { requirement: "Use Takeoff Flight Path and Climb Gradient charts for obstacle clearance." } },
    ],
    interpolation: "none",
    notes: [
      "Takeoff may use flaps 8° or 20°; FlightSafety states contaminated-runway takeoff requires flaps 20°.",
      "Graphical AFM-derived charts remain chart-based. No undocumented interpolation or polynomial approximation is used here.",
    ],
    sources: [fsi(20, "Takeoff — Maximum Allowable Takeoff Weight / Takeoff Weight Limits", "20-6–20-7")],
  },
  {
    id: "fsi-climb-segment-requirements",
    title: "Takeoff / approach climb certification segments",
    kind: "reference-table",
    axes: [{ key: "segment", label: "Segment", values: ["First", "Second", "Final", "Approach", "Landing"] }],
    outputs: [
      { key: "engines", label: "Engines" },
      { key: "flaps", label: "Flaps" },
      { key: "gear", label: "Gear" },
      { key: "thrust", label: "Thrust" },
      { key: "minimumGradient", label: "Minimum gross gradient" },
    ],
    rows: [
      { inputs: { segment: "First" }, outputs: { engines: 1, flaps: "8° or 20°", gear: "DOWN → retracting", thrust: "Takeoff", minimumGradient: "Positive" } },
      { inputs: { segment: "Second" }, outputs: { engines: 1, flaps: "8° or 20°", gear: "UP", thrust: "Takeoff", minimumGradient: "2.4%" } },
      { inputs: { segment: "Final" }, outputs: { engines: 1, flaps: "UP / 0°", gear: "UP", thrust: "Maximum continuous", minimumGradient: "1.2%" } },
      { inputs: { segment: "Approach" }, outputs: { engines: 1, flaps: "20°", gear: "UP", thrust: "Takeoff", minimumGradient: "2.1%" } },
      { inputs: { segment: "Landing" }, outputs: { engines: 2, flaps: "40°", gear: "DOWN", thrust: "Takeoff", minimumGradient: "3.2%" } },
    ],
    interpolation: "none",
    sources: [fsi(20, "Climb Segments / Table 20-2", "20-6–20-8")],
  },
  {
    id: "fsi-all-engine-climb-schedule",
    title: "All-engine climb schedule",
    description: "FlightSafety Chapter 20 climb-performance schedule.",
    kind: "reference-table",
    axes: [{ key: "altitudeBand", label: "Altitude band", values: ["To 32,000 ft", "Above 32,000 ft"] }],
    outputs: [{ key: "target", label: "Target" }],
    rows: [
      { inputs: { altitudeBand: "To 32,000 ft" }, outputs: { target: "250 KIAS" } },
      { inputs: { altitudeBand: "Above 32,000 ft" }, outputs: { target: "M 0.70" } },
    ],
    interpolation: "none",
    sources: [fsi(20, "Climb Performance", "20-25–20-27")],
  },
  {
    id: "fsi-oei-max-range-descent",
    title: "One-engine maximum-range descent / drift-down speed schedule",
    kind: "reference-table",
    axes: [{ key: "altitudeBand", label: "Altitude band", values: ["45,000–33,500 ft", "33,500–26,500 ft", "Below 26,500 ft"] }],
    outputs: [{ key: "speed", label: "Speed" }],
    rows: [
      { inputs: { altitudeBand: "45,000–33,500 ft" }, outputs: { speed: "170 KIAS" } },
      { inputs: { altitudeBand: "33,500–26,500 ft" }, outputs: { speed: "M 0.50" } },
      { inputs: { altitudeBand: "Below 26,500 ft" }, outputs: { speed: "200 KIAS" } },
    ],
    interpolation: "none",
    notes: ["Set maximum continuous thrust after the engine failure; the Chapter 18 drift-down profile uses the same 170 KIAS / M0.50 / 200 KIAS transition concept."],
    sources: [fsi(20, "Maximum Range Descent — One Engine", "20-29"), fsi(18, "Single-Engine Drift Down", "18-36")],
  },
  {
    id: "fsi-normal-cruise-example",
    title: "Normal-cruise source example",
    description: "An exact worked FlightSafety example retained as an auditable source row, not generalized into a fabricated cruise model.",
    kind: "reference-table",
    axes: [
      { key: "weight", label: "Gross weight", unit: "lb", values: [15000] },
      { key: "altitude", label: "Pressure altitude", unit: "ft", values: [41000] },
      { key: "temperature", label: "Temperature", values: ["ISA"] },
      { key: "mach", label: "Cruise Mach", values: [0.75] },
    ],
    outputs: [
      { key: "tas", label: "True airspeed", unit: "KTAS" },
      { key: "fuelFlow", label: "Total fuel flow", unit: "lb/hr" },
    ],
    rows: [{ inputs: { weight: 15000, altitude: 41000, temperature: "ISA", mach: 0.75 }, outputs: { tas: 432, fuelFlow: 1076 } }],
    interpolation: "none",
    notes: ["FlightSafety's worked example uses approximately 1.5 hr and 1,619 lb for a 650 NM no-wind cruise segment at these conditions."],
    sources: [fsi(20, "Cruise Performance / Normal Cruise", "20-27–20-29")],
  },
  {
    id: "fsi-landing-distance-workflow",
    title: "Landing distance — source-chart workflow",
    description: "The source landing chart uses altitude, OAT, weight, wind, runway gradient and anti-skid. Exact chart reading remains required; FlyTally does not invent chart interpolation.",
    kind: "reference-table",
    axes: [{ key: "step", label: "Planning step", values: ["Actual dry distance", "Factored distance", "Wet / contaminated correction", "Runway check"] }],
    outputs: [{ key: "action", label: "Action" }],
    rows: [
      { inputs: { step: "Actual dry distance" }, outputs: { action: "Read the applicable actual landing distance chart for altitude, OAT, gross weight, wind, runway gradient and anti-skid." } },
      { inputs: { step: "Factored distance" }, outputs: { action: "Apply the applicable regulatory/operational factored-distance requirement; FlightSafety describes the 60% rule as actual distance ÷ 0.60 (≈ ×1.67)." } },
      { inputs: { step: "Wet / contaminated correction" }, outputs: { action: "Apply the published wet or contaminated runway factor only after obtaining the corrected dry distance." } },
      { inputs: { step: "Runway check" }, outputs: { action: "Calculated actual/factored landing distance must be below LDA." } },
    ],
    interpolation: "none",
    notes: ["FlightSafety wet-runway basis: flaps 40°, anti-skid ON, runway gradient between -2% and +2%.", "Contaminated-runway basis includes flaps 40°, anti-skid ON, no tailwind, runway gradient -1% to +2%."],
    sources: [fsi(20, "Landing Distance / Wet and Contaminated Runway", "20-34–20-37")],
  },
  {
    id: "fsi-flaps-up-landing-correction",
    title: "Flaps-up landing training correction",
    kind: "reference-table",
    axes: [{ key: "condition", label: "Condition", values: ["Flaps-up landing"] }],
    outputs: [{ key: "distanceCorrection", label: "Landing-distance correction" }],
    rows: [{ inputs: { condition: "Flaps-up landing" }, outputs: { distanceCorrection: "Normal landing distance × 1.35" } }],
    interpolation: "none",
    sources: [fsi(18, "Flaps Up Landing", "18-30")],
  },
  {
    id: "jaydee-takeoff-speeds",
    title: "JayDee 35A takeoff speed quick table — supplementary",
    description: "Complete takeoff VR/V2 table from JayDee v1.35.WIP1. Kept as a clearly identified simulator-workflow supplement; it does not replace AFM-derived takeoff computation.",
    kind: "lookup-table",
    axes: [
      { key: "grossWeight", label: "Gross weight", unit: "lb", values: [13000, 14000, 15000, 16000, 17000, 18000] },
      { key: "flaps", label: "Flaps", unit: "deg", values: [8, 20] },
    ],
    outputs: [{ key: "vr", label: "VR", unit: "KIAS" }, { key: "v2", label: "V2", unit: "KIAS" }],
    rows: takeoffSpeedRows.map(([grossWeight, flaps, vr, v2]) => ({ inputs: { grossWeight, flaps }, outputs: { vr, v2 } })),
    interpolation: "none",
    applicability: { variants: ["35A"], note: "JayDee 35A simulator-workflow source." },
    notes: ["V1 is not supplied in this JayDee table; do not derive it from VR or V2.", "No interpolation is performed between listed weights."],
    sources: [jaydee("II — Performance / Takeoff Speeds KIAS")],
  },
  {
    id: "jaydee-takeoff-trim",
    title: "JayDee 35A takeoff trim — supplementary",
    kind: "reference-table",
    axes: [{ key: "cg", label: "CG (% MAC band)", values: ["5–20", "22", "24", "26", "28/30"] }],
    outputs: [{ key: "trim", label: "Trim" }],
    rows: [
      { inputs: { cg: "5–20" }, outputs: { trim: "7.7 to 7.3" } },
      { inputs: { cg: "22" }, outputs: { trim: 6.8 } },
      { inputs: { cg: "24" }, outputs: { trim: 6.2 } },
      { inputs: { cg: "26" }, outputs: { trim: 5.6 } },
      { inputs: { cg: "28/30" }, outputs: { trim: 5 } },
    ],
    interpolation: "none",
    applicability: { variants: ["35A"] },
    sources: [jaydee("II — Performance / Takeoff Trim")],
  },
  {
    id: "jaydee-takeoff-n1-reference",
    title: "JayDee 35A takeoff N1 reference — supplementary",
    kind: "reference-table",
    axes: [{ key: "reference", label: "Reference", values: ["ISA / sea level", "Per 5°C below ISA", "Per 5°C above ISA", "Per 1,000 ft above sea level", "Full anti-ice"] }],
    outputs: [{ key: "n1", label: "N1 reference / adjustment" }],
    rows: [
      { inputs: { reference: "ISA / sea level" }, outputs: { n1: "96.0%" } },
      { inputs: { reference: "Per 5°C below ISA" }, outputs: { n1: "-1%" } },
      { inputs: { reference: "Per 5°C above ISA" }, outputs: { n1: "+1%" } },
      { inputs: { reference: "Per 1,000 ft above sea level" }, outputs: { n1: "+1%" } },
      { inputs: { reference: "Full anti-ice" }, outputs: { n1: "subtract 3%" } },
    ],
    interpolation: "none",
    applicability: { variants: ["35A"] },
    notes: ["Apply the ambient-temperature hard N1 cap dataset as a separate ceiling."],
    sources: [jaydee("II — Performance / Takeoff Power")],
  },
  {
    id: "jaydee-hard-n1-ambient-cap",
    title: "JayDee 35A hard N1 limit by ambient temperature — supplementary",
    kind: "reference-table",
    axes: [{ key: "ambient", label: "Ambient temperature", unit: "°C", values: [-17, 5, 15, 25, 37, 48] }],
    outputs: [{ key: "n1Limit", label: "Hard N1 limit", unit: "%" }],
    rows: [[-17, 100], [5, 99], [15, 98], [25, 96], [37, 93], [48, 90]].map(([ambient, n1Limit]) => ({ inputs: { ambient }, outputs: { n1Limit } })),
    interpolation: "none",
    applicability: { variants: ["35A"] },
    sources: [jaydee("II — Performance / Hard N1 Limits by Ambient Temp")],
  },
  {
    id: "jaydee-max-continuous-n1",
    title: "JayDee 35A maximum continuous N1 — supplementary",
    description: "Climb/cruise maximum-continuous N1 quick table exactly as listed by JayDee; temperature adjustments are per 5°C below/above the reference RAT.",
    kind: "reference-table",
    axes: [{ key: "altitude", label: "Altitude", unit: "ft", values: maxContinuousRows.map(([altitude]) => altitude) }],
    outputs: [
      { key: "rat", label: "Reference RAT", unit: "°C" },
      { key: "n1", label: "N1", unit: "%" },
      { key: "below", label: "Per 5°C below" },
      { key: "above", label: "Per 5°C above" },
    ],
    rows: maxContinuousRows.map(([altitude, rat, n1, below, above]) => ({ inputs: { altitude }, outputs: { rat, n1, below, above } })),
    interpolation: "none",
    applicability: { variants: ["35A"] },
    notes: ["JayDee states full anti-ice ON: subtract 2.5% N1.", "No interpolation between altitude rows is performed by FlyTally."],
    sources: [jaydee("II — Performance / Max Continuous Power (Climb and Cruise)")],
  },
  {
    id: "jaydee-enroute-climb",
    title: "JayDee 35A enroute climb profile — supplementary",
    kind: "reference-table",
    axes: [
      { key: "engineState", label: "Engine state", values: ["All engines", "Single engine"] },
      { key: "altitudeBand", label: "Altitude band", values: ["≤27,000 ft", "27,000–32,500 ft", "32,500–33,000 ft", ">33,000 ft"] },
    ],
    outputs: [{ key: "target", label: "Target" }],
    rows: [
      { inputs: { engineState: "All engines", altitudeBand: "≤27,000 ft" }, outputs: { target: "250 KIAS" } },
      { inputs: { engineState: "All engines", altitudeBand: "27,000–32,500 ft" }, outputs: { target: "250 KIAS" } },
      { inputs: { engineState: "All engines", altitudeBand: "32,500–33,000 ft" }, outputs: { target: "M 0.70" } },
      { inputs: { engineState: "All engines", altitudeBand: ">33,000 ft" }, outputs: { target: "M 0.70" } },
      { inputs: { engineState: "Single engine", altitudeBand: "≤27,000 ft" }, outputs: { target: "200 KIAS" } },
      { inputs: { engineState: "Single engine", altitudeBand: "27,000–32,500 ft" }, outputs: { target: "M 0.50" } },
      { inputs: { engineState: "Single engine", altitudeBand: "32,500–33,000 ft" }, outputs: { target: "M 0.50" } },
      { inputs: { engineState: "Single engine", altitudeBand: ">33,000 ft" }, outputs: { target: "170 KIAS" } },
    ],
    interpolation: "none",
    applicability: { variants: ["35A"] },
    sources: [jaydee("II — Performance / Enroute Climb Profile")],
  },
  {
    id: "jaydee-landing-vref",
    title: "JayDee 35A landing VREF — supplementary",
    kind: "lookup-table",
    axes: [{ key: "grossWeight", label: "Gross weight", unit: "lb", values: vrefRows.map(([grossWeight]) => grossWeight) }],
    outputs: [{ key: "vref", label: "VREF", unit: "KIAS" }],
    rows: vrefRows.map(([grossWeight, vref]) => ({ inputs: { grossWeight }, outputs: { vref } })),
    interpolation: "none",
    applicability: { variants: ["35A"] },
    notes: ["JayDee go-around cue: gear down/flaps 40° = VREF; gear up/flaps 20° = VREF + 7."],
    sources: [jaydee("II — Performance / Landing Approach Speed KIAS")],
  },
  {
    id: "jaydee-tod-reference",
    title: "JayDee top-of-descent rule — supplementary",
    kind: "reference-table",
    axes: [{ key: "path", label: "Path", values: ["3°", "4°", "5°"] }],
    outputs: [{ key: "rule", label: "Rule" }],
    rows: [
      { inputs: { path: "3°" }, outputs: { rule: "TOD NM = altitude/1,000 × 3 + 10" } },
      { inputs: { path: "4°" }, outputs: { rule: "TOD NM = altitude/1,000 × 2.5 + 10" } },
      { inputs: { path: "5°" }, outputs: { rule: "TOD NM = altitude/1,000 × 2 + 10" } },
    ],
    interpolation: "none",
    applicability: { variants: ["35A"] },
    sources: [jaydee("II — Performance / TOD")],
  },
  {
    id: "flysimware-model-performance-envelope",
    title: "Flysimware modeled-aircraft headline performance — implementation reference",
    kind: "reference-table",
    axes: [{ key: "metric", label: "Metric", values: ["Normal range", "Maximum range", "Service ceiling", "Balanced field length", "Landing distance", "Maximum speed", "Normal cruise", "Economy cruise", "Fuel capacity"] }],
    outputs: [{ key: "value", label: "Published implementation value" }],
    rows: [
      { inputs: { metric: "Normal range" }, outputs: { value: "1,700–2,000 NM" } },
      { inputs: { metric: "Maximum range" }, outputs: { value: "2,000–2,100 NM" } },
      { inputs: { metric: "Service ceiling" }, outputs: { value: "45,000 ft" } },
      { inputs: { metric: "Balanced field length" }, outputs: { value: "5,000–6,000 ft" } },
      { inputs: { metric: "Landing distance" }, outputs: { value: "3,000 ft" } },
      { inputs: { metric: "Maximum speed" }, outputs: { value: "451 kt" } },
      { inputs: { metric: "Normal cruise" }, outputs: { value: "424 kt" } },
      { inputs: { metric: "Economy cruise" }, outputs: { value: "377 kt" } },
      { inputs: { metric: "Fuel capacity" }, outputs: { value: "6,238 lb" } },
    ],
    interpolation: "none",
    applicability: { variants: ["35A"], note: "Flysimware model implementation data." },
    notes: ["These are product headline/reference figures, not an AFM dispatch calculation."],
    sources: [flysimware("Aircraft Information — Technical Specifications / Performance", "technical specifications")],
  },
];

export const learjet3536CompletePerformance: AircraftPerformanceContent = {
  ...learjet3536NativePerformance,
  title: "Learjet 35/36 Pilot Performance Reference",
  sourceNote:
    "Primary planning logic and configuration limits are retained from FlightSafety/CAE training references. Exact graphical AFM-derived charts are not replaced by invented equations. The complete JayDee 35A quick-performance page is retained as a clearly labelled simulator-workflow supplement, and Flysimware headline values as implementation reference.",
  disclaimer: commonBoundary,
  datasets: [...learjet3536NativePerformance.datasets, ...pilotDatasets],
};

export const learjet3536CompleteLimitations: AircraftLimitationsContent = {
  ...learjet3536NativeLimitations,
  title: "Learjet 35/36 Pilot Limitations & Operating Boundaries",
  sourceNote:
    "Configuration-specific CAE/FlightSafety limits remain explicit. JayDee values are included only as a 35A simulator-workflow supplement and never silently override the training references.",
  disclaimer: commonBoundary,
  groups: [
    ...learjet3536NativeLimitations.groups,
    {
      id: "primary-operating-boundaries",
      title: "Primary operating boundaries",
      items: [
        { id: "max-operating-altitude", label: "Maximum operating altitude", value: 45000, unit: "ft", sources: [fsi(1, "Aircraft General — General", "1-1")] },
        { id: "minimum-wing-fuel-takeoff", label: "Wing fuel minimum for takeoff / intentional go-around", value: 600, unit: "lb", sources: [fsi(5, "Fuel Tanks and Tank Venting — General", "5-3")] },
        { id: "spoilers-flaps-airborne", label: "Spoilers with flaps extended while airborne", value: "PROHIBITED", notices: [{ kind: "warning", text: "Do not extend spoilers with flaps extended while airborne." }], sources: [cae("Flight Controls — Spoilers", "3-28")] },
        { id: "spoilers-above-vmo-mmo", label: "Spoilers above VMO/MMO", value: "PROHIBITED", notices: [{ kind: "warning", text: "Do not extend spoilers or operate with spoilers deployed above VMO/MMO." }], sources: [cae("Flight Controls — Spoilers", "3-28")] },
        { id: "stall-warning-flight", label: "Stall warning systems in flight", value: "Both ON and operating", condition: "Except as directed by applicable emergency/abnormal or maintenance procedures.", sources: [cae("Flight Controls — Stall Warning System", "3-28")] },
      ],
      sources: [fsi(1, "Aircraft General", "1-1"), cae("Flight Controls", "3-28")],
    },
    {
      id: "cae-century-iii-fc200-airspeeds",
      title: "CAE Century III wing / FC-200 / RAS AAK 76-4 — airspeed limits",
      items: [
        { id: "cae-fc200-mmo", label: "MMO", value: 0.83, unit: "Mach", condition: "Century III wing / FC-200 / RAS-AAK 76-4 configuration.", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-missing-bles", label: "MMO with missing BLEs", value: 0.78, unit: "Mach", condition: "S/N 35-279 and subsequent; 36-045 and subsequent; prior aircraft with AAK 79-10 or AMK 83-5.", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-machtrim-inop", label: "Mach trim/autopilot disengaged or inoperative", value: 0.74, unit: "Mach", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-puller-inop", label: "Stick puller inoperative", value: 0.74, unit: "Mach", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vmo-low", label: "VMO — sea level to 14,000 ft", value: 307, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vmo-high", label: "VMO — above 14,000 ft", value: 359, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vle", label: "VLE", value: 265, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vlo", label: "VLO", value: 202, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vfe-1-8", label: "VFE — flaps 1° to 8°", value: 198, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vfe-9-20", label: "VFE — flaps 9° to 20°", value: 183, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vfe-21-40", label: "VFE — flaps 21° to 40°", value: 153, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
        { id: "cae-fc200-vmca", label: "VMCA at 0°F / -18°C", value: 112, unit: "KIAS", sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")] },
      ],
      sources: [cae("Limitations — Century III Wing / FC-200 / RAS-AAK 76-4", "3-9")],
    },
    {
      id: "cae-rvsm-fc530-overspeed-reference",
      title: "CAE typical RVSM / FC-530 overspeed warning reference",
      items: [
        { id: "cae-fc530-machtrim-074", label: "Mach trim inoperative / autopilot not engaged warning", value: 0.74, unit: "Mach", sources: [cae("Flight Controls — Mach/Overspeed Warning", "4E-10–4E-11")] },
        { id: "cae-fc530-low-vmo", label: "Overspeed horn — below 8,000 ft", value: 300, unit: "KIAS", condition: "Typical RVSM or FC-530 installation described by CAE; verify the applicable AFM supplement.", sources: [cae("Flight Controls — Mach/Overspeed Warning", "4E-10–4E-11")] },
        { id: "cae-fc530-high-vmo", label: "Overspeed horn — above 8,000 ft", value: "350 KIAS / M 0.81", condition: "Typical RVSM or FC-530 installation described by CAE; verify the applicable AFM supplement.", sources: [cae("Flight Controls — Mach/Overspeed Warning", "4E-10–4E-11")] },
        { id: "cae-fc530-puller", label: "Stick puller overspeed activation", value: "354 KIAS / M 0.82", condition: "Typical RVSM or FC-530 installation described by CAE.", sources: [cae("Flight Controls — Mach/Overspeed Warning", "4E-10–4E-11")] },
      ],
      sources: [cae("Flight Controls — Mach/Overspeed Warning", "4E-10–4E-11")],
    },
    {
      id: "jaydee-35a-speed-weight-limits",
      title: "JayDee 35A quick limits — supplementary",
      items: [
        { id: "jd-mtow", label: "Maximum takeoff weight", value: 18300, unit: "lb", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-mlw", label: "Maximum landing weight", value: 15300, unit: "lb", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-mzfw-tip", label: "Maximum zero wing & tip fuel weight", value: 13500, unit: "lb", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-load-clean", label: "Load factor — flaps retracted", value: "+3.0 g to -1.0 g", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-load-flaps", label: "Load factor — flaps extended", value: "+2.0 g to 0.0 g", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-altitude", label: "Maximum operating altitude", value: 45000, unit: "ft", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-vmo-low", label: "VMO up to 14,000 ft", value: 307, unit: "KIAS", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-vmo-high", label: "VMO above 14,000 ft", value: 359, unit: "KIAS", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-mmo", label: "MMO", value: 0.83, unit: "Mach", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-vfe-8-20", label: "VFE — flaps 8° to 20°", value: 200, unit: "KIAS", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-vfe-40", label: "VFE — flaps 40°", value: 150, unit: "KIAS", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-vlo", label: "VLO", value: 200, unit: "KIAS", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
        { id: "jd-vle", label: "VLE", value: 260, unit: "KIAS", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")] },
      ],
      sources: [jaydee("I — Limitations / Weight, Load Factor and Speeds")],
    },
    {
      id: "jaydee-35a-engine-limits",
      title: "JayDee 35A engine limits — supplementary",
      items: [
        { id: "jd-n1n2-maint", label: "N1 / N2 overspeed — maintenance required", value: "105%", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-n1n2-5sec", label: "N1 / N2 transient — 5 seconds", value: "103–105%", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-n1n2-1min", label: "N1 / N2 transient — 1 minute", value: "100–103%", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-start-itt-5", label: "Engine-start ITT — max 5 sec", value: 930, unit: "°C", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-start-itt-10", label: "Engine-start ITT — max 10 sec", value: 880, unit: "°C", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-start-itt-cont", label: "Engine-start ITT — continuous", value: 860, unit: "°C", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-other-itt-10", label: "ITT all other — max 10 sec", value: 870, unit: "°C", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-other-itt-5min", label: "ITT all other — max 5 min", value: 860, unit: "°C", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
        { id: "jd-other-itt-cont", label: "ITT all other — continuous", value: 832, unit: "°C", applicability: { variants: ["35A"] }, sources: [jaydee("I — Limitations / Engine Limitations")] },
      ],
      sources: [jaydee("I — Limitations / Engine Limitations")],
    },
    {
      id: "cae-engine-operating-cues",
      title: "CAE powerplant operating cues",
      items: [
        { id: "cae-oil-pressure-normal", label: "Oil pressure regulator reference", value: "approximately 42 PSI", sources: [cae("Powerplant — Lubrication", "4K-5–4K-6")] },
        { id: "cae-oil-warm", label: "Power above idle with cold oil", value: "Avoid below 30°C oil temperature", condition: "CAE notes that if OAT prevents reaching 30°C at idle, power may be increased as required to warm oil before takeoff.", sources: [cae("Expanded Normal Procedures — Starting", "2B-80")] },
        { id: "cae-cold-hyd-warm", label: "Cold-soak hydraulic warm-up", value: "At least 3 min engine operation", condition: "Outside temperature below -13°C before takeoff.", sources: [cae("Expanded Normal Procedures — Starting", "2B-80")] },
        { id: "cae-spr-temp", label: "SPR use", value: "Below 0°F / -17°C starts", condition: "Release SPR at approximately 300–400°C ITT; do not use except during engine start.", sources: [cae("Expanded Normal Procedures — Starting", "2B-80")] },
        { id: "cae-start-disengage", label: "Starter / ignition automatic termination", value: "approximately 45% N2", condition: "CAE engine description; FlightSafety notes 45% or 50% depending on fuel-computer model.", sources: [cae("Powerplant — Ignition System", "4K-6–4K-7"), fsi(7, "Other Start Functions", "7-20")] },
        { id: "cae-engine-ultimate-n1", label: "Fuel-control governing limit", value: "105% RPM", condition: "CAE describes metering-valve modulation to limit engine RPM.", sources: [cae("Powerplant — Fuel Control System", "4K-7")] },
        { id: "cae-ultimate-overspeed", label: "Electronic ultimate overspeed protection", value: "N1 >109% or N2 >110% → fuel shutoff", sources: [cae("Powerplant — Fuel Control System", "4K-7")], notices: [{ kind: "warning", text: "This is protection-system logic, not a normal operating target." }] },
      ],
      sources: [cae("Powerplant", "4K-5–4K-9"), cae("Expanded Normal Procedures — Starting", "2B-80")],
    },
  ],
};
