import { learjet3536NativeAbnormal } from "./learjet-native-abnormal.ts";
import type { AircraftAbnormalEmergencyContent, AircraftAbnormalEmergencyScenario } from "./universal-abnormal-emergency.ts";
import type { TrainingSourceReference } from "./universal-aircraft-content.ts";

const FSI = "fsi-learjet-35-36-ptm-r1-1";
const src = (section: string, pageLabel: string): TrainingSourceReference => ({ manualId: FSI, chapter: "18", section, pageLabel });
const boundary = "FlightSafety Chapter 18 is a training/SOP reference and explicitly does not supersede the current AFM, approved supplements, operator SOPs or QRH. The sequence below is retained as training content, not represented as an approved aircraft QRH.";

const extraScenarios: readonly AircraftAbnormalEmergencyScenario[] = [
  {
    id: "emergency-descent-training-profile",
    title: "Emergency descent",
    category: "Pressurization / emergency descent",
    phase: "Cruise",
    difficulty: "core",
    minutes: 6,
    summary: "FlightSafety's AFM-based training profile for establishing a rapid descent while using oxygen, drag and the published speed boundary.",
    setup: "A condition requiring an emergency descent is recognized at altitude. The exercise starts before the descent is established.",
    objectives: ["Establish the emergency-descent configuration without losing aircraft control", "Understand the MMO/VLE speed target", "Sequence level-off cleanup correctly"],
    boundaryNote: boundary,
    stages: [
      {
        id: "entry",
        label: "Entry",
        prompt: "What entry actions does the FlightSafety Figure 18-10 training profile specify?",
        expectedResponse: ["Crew oxygen masks ON and select 100% oxygen.", "Power IDLE.", "Autopilot DISENGAGED.", "Spoilers EXTENDED.", "Landing gear DOWN when below MMO/VLE.", "Establish approximately 10–15° nose-down pitch."],
        explanation: "The profile combines crew oxygen with idle thrust, drag devices and a deliberate pitch-down to establish the descent.",
        sources: [src("Emergency Descent — Figure 18-10", "18-27")],
      },
      {
        id: "cabin",
        label: "Cabin oxygen",
        prompt: "What passenger-oxygen valve positions are shown in the training profile?",
        expectedResponse: ["PASS OXY valve — NORMAL.", "PASS MASK valve — MANUAL."],
        explanation: "These positions are shown in the FlightSafety emergency-descent figure; current aircraft/operator documentation remains controlling.",
        sources: [src("Emergency Descent — Figure 18-10", "18-27")],
      },
      {
        id: "descent",
        label: "Descent",
        prompt: "How is the descent speed established and maintained?",
        expectedResponse: ["Maintain the initial pitch attitude until reaching MMO/VLE.", "Then adjust pitch to maintain the applicable MMO/VMO boundary."],
        explanation: "FlightSafety describes holding 10–15° nose down until the airplane accelerates to the limiting speed, then adjusting pitch to remain on the limit.",
        sources: [src("Emergency Descent", "18-27")],
      },
      {
        id: "leveloff",
        label: "Level-off",
        prompt: "What cleanup is shown at level-off?",
        expectedResponse: ["Retract spoilers.", "Retract gear as necessary only if airspeed did not exceed VLE.", "Set power as required."],
        explanation: "The crew should determine the desired level-off altitude after the descent is established and clean up without exceeding gear limitations.",
        sources: [src("Emergency Descent — Figure 18-10", "18-27")],
      },
    ],
    debrief: ["Was oxygen established before becoming absorbed in the descent?", "Did you respect the MMO/VLE/VMO boundary?", "Did you avoid retracting gear after an overspeed beyond VLE?"],
  },
  {
    id: "unusual-attitude-nose-high",
    title: "Unusual attitude recovery — nose high",
    category: "Aircraft control",
    phase: "Any airborne phase",
    difficulty: "advanced",
    minutes: 5,
    summary: "Reduce angle of attack without creating negative G, add power and use bank to help lower the nose while keeping the AOA indication in the green area.",
    setup: "The aircraft is in a nose-high, low-speed unusual attitude with pitch and roll attitude identified.",
    objectives: ["Prioritize angle-of-attack reduction", "Avoid prolonged negative G", "Use bank and thrust deliberately"],
    boundaryNote: boundary,
    stages: [
      {
        id: "recover",
        label: "Recover",
        prompt: "What simultaneous recovery actions are shown in Figure 18-8?",
        expectedResponse: ["Push forward on the yoke enough to reduce AOA without creating negative G.", "Maintain or roll into 60–90° bank as required.", "Advance power as required."],
        explanation: "The training profile uses bank, power and reduced AOA to let the nose descend without stalling or imposing prolonged negative G.",
        sources: [src("Unusual Attitude Recovery — Nose High / Figure 18-8", "18-25")],
      },
      {
        id: "aoa",
        label: "AOA control",
        prompt: "What should the angle-of-attack indication show during recovery?",
        expectedResponse: ["Maintain the angle-of-attack indicator in the green area."],
        explanation: "FlightSafety explicitly calls for AOA cross-check during the recovery.",
        sources: [src("Unusual Attitude Recovery — Nose High", "18-25")],
      },
      {
        id: "horizon",
        label: "Through horizon",
        prompt: "Once the nose passes the horizon, what does the profile call for?",
        expectedResponse: ["When airspeed is greater than 180 KIAS, roll wings level.", "Reduce power as required."],
        explanation: "The figure sequences roll-out and power reduction after the nose has come through the horizon and speed has recovered.",
        sources: [src("Unusual Attitude Recovery — Nose High / Figure 18-8", "18-25")],
      },
    ],
    debrief: ["Did you reduce AOA rather than try to hold altitude?", "Did you avoid negative G?", "Did you cross-check AOA and attitude references?"],
  },
  {
    id: "unusual-attitude-nose-low",
    title: "Unusual attitude recovery — nose low",
    category: "Aircraft control",
    phase: "Any airborne phase",
    difficulty: "advanced",
    minutes: 5,
    summary: "Reduce thrust and roll wings level before applying nose-up elevator; keep speed below VMO/MMO and do not use spoilers in the recovery.",
    setup: "The aircraft is in a nose-low, high-speed unusual attitude with pitch and roll attitude identified.",
    objectives: ["Unload the high-speed situation without over-G", "Sequence roll before pull", "Respect the spoiler prohibition"],
    boundaryNote: boundary,
    stages: [
      {
        id: "initial",
        label: "Initial recovery",
        prompt: "What two actions are simultaneous at the start of the nose-low recovery?",
        expectedResponse: ["Roll toward wings level.", "Reduce power to IDLE."],
        explanation: "The source emphasizes simultaneously reducing thrust and bank before using elevator to raise the nose.",
        sources: [src("Unusual Attitude Recovery — Nose Low / Figure 18-9", "18-26")],
      },
      {
        id: "pitch",
        label: "Pitch recovery",
        prompt: "When is nose-up elevator/pitch trim applied?",
        expectedResponse: ["Only as the bank angle approaches wings level, use elevator and pitch trim nose-up as required."],
        explanation: "Pulling while heavily banked increases loading and does not efficiently recover altitude.",
        sources: [src("Unusual Attitude Recovery — Nose Low", "18-26")],
      },
      {
        id: "drag",
        label: "Drag devices",
        prompt: "May spoilers be used in this nose-low recovery?",
        expectedResponse: ["No. FlightSafety specifically says spoilers must not be used during recovery from a nose-low unusual attitude.", "If Mach/airspeed or attitude is severe/extreme/unknown, the source notes that landing gear may be extended to aid recovery."],
        explanation: "The gear note is an extreme-case training reference; current AFM/QRH limitations remain controlling.",
        sources: [src("Unusual Attitude Recovery — Nose Low", "18-26")],
      },
    ],
    debrief: ["Did you roll before pulling?", "Did you keep the recovery below VMO/MMO?", "Did you avoid spoiler deployment?"],
  },
  {
    id: "approach-to-stall-recovery",
    title: "Approach-to-stall recovery",
    category: "Aircraft control",
    phase: "Training maneuver",
    difficulty: "core",
    minutes: 7,
    summary: "At the first stall indication, reduce AOA, apply takeoff power, level the wings and accelerate out of the stall condition before returning to the desired flight path.",
    setup: "Training approach to a stall in clean, takeoff or landing configuration. FlightSafety states that actual-aircraft approach-to-stall training should not be accomplished below 5,000 ft AGL.",
    objectives: ["Recognize the first stall indication", "Prioritize AOA reduction", "Understand configuration-specific cleanup"],
    boundaryNote: boundary,
    stages: [
      {
        id: "recognition",
        label: "Recognize",
        prompt: "When does the recovery begin?",
        expectedResponse: ["At the first indication of an impending stall: stick shaker/stall warning as AOA enters the yellow band, or aerodynamic buffet if it occurs first."],
        explanation: "The source explicitly does not wait for a fully developed stall.",
        sources: [src("Approach to Stall", "18-22")],
      },
      {
        id: "core-recovery",
        label: "Core recovery",
        prompt: "What is common to the clean/takeoff/landing recovery profiles?",
        expectedResponse: ["Lower pitch attitude to reduce angle of attack.", "Set thrust levers to takeoff/maximum power.", "Level the wings.", "Accelerate out of the stall condition."],
        explanation: "If below stall-warning AOA, FlightSafety says immediate AOA reduction takes priority over maintaining altitude.",
        sources: [src("Approach to Stall — Figures 18-5 through 18-7", "18-22–18-24")],
      },
      {
        id: "landing-cleanup",
        label: "Landing-config cleanup",
        prompt: "What cleanup sequence is shown for the landing-configuration recovery?",
        expectedResponse: ["When airspeed is greater than VREF, set flaps 20°.", "At positive rate, gear UP.", "At VREF + 30, flaps UP.", "Return to the desired flight path."],
        explanation: "The landing-configuration figure converts the recovery into the same general configuration used for a missed approach.",
        sources: [src("Approach to Stall — Landing Configuration / Figure 18-7", "18-24")],
      },
    ],
    debrief: ["Was AOA reduction immediate?", "Did you avoid sacrificing recovery for altitude hold?", "Was configuration cleaned up only after speed and positive climb were established?"],
  },
  {
    id: "windshear-flight-path-marginal",
    title: "Windshear recovery — flight-path control marginal",
    category: "Windshear",
    phase: "Takeoff / approach / landing",
    difficulty: "advanced",
    minutes: 6,
    summary: "Use maximum available thrust, follow recovery guidance/pitch limits, accept lower airspeed if necessary and freeze configuration until clear of the shear.",
    setup: "A windshear encounter has progressed to marginal flight-path control with terrain/obstacle contact a possibility.",
    objectives: ["Prioritize flight path over target airspeed", "Keep configuration fixed", "Use PM trend callouts effectively"],
    boundaryNote: boundary,
    stages: [
      {
        id: "thrust",
        label: "Thrust",
        prompt: "What thrust action is specified when flight-path control is marginal?",
        expectedResponse: ["Advance thrust levers to takeoff / maximum go-around thrust; use all available thrust if ground or obstacle contact is possible."],
        explanation: "The source prioritizes energy and terrain clearance over normal target-setting precision.",
        sources: [src("Windshear — If Encountered and Flight Path Control Is Marginal", "18-39–18-40")],
      },
      {
        id: "monitor",
        label: "PM monitor",
        prompt: "What should the PM continuously monitor and call?",
        expectedResponse: ["Vertical flight path, thrust, airspeed and trend, rate of climb, pitch and altitude; make directive callouts for significant trends/deviations."],
        explanation: "FlightSafety explicitly assigns the PM continuous flight-path monitoring and directive commentary.",
        sources: [src("Windshear — If Encountered and Flight Path Control Is Marginal", "18-39")],
      },
      {
        id: "pitch",
        label: "Pitch / airspeed",
        prompt: "What tradeoff is accepted during the escape?",
        expectedResponse: ["Follow recovery guidance without exceeding pitch limits for as long as terrain contact remains a threat.", "Accept lower-than-normal indicated airspeed, up to intermittent stick shaker if necessary."],
        explanation: "The goal is escape flight path, not normal speed control.",
        sources: [src("Windshear — If Encountered and Flight Path Control Is Marginal", "18-39")],
      },
      {
        id: "configuration",
        label: "Configuration",
        prompt: "What happens to flap, gear and trim during the encounter?",
        expectedResponse: ["Maintain configuration; do not change flap, gear or trim until positively clear of the shear."],
        explanation: "FlightSafety warns against configuration changes while the encounter is active and notes that multiple shear encounters can occur.",
        sources: [src("Windshear — If Encountered and Flight Path Control Is Marginal", "18-39–18-40")],
      },
      {
        id: "clear",
        label: "When clear",
        prompt: "What follows after the shear is cleared?",
        expectedResponse: ["Proceed with a normal climb after a positive climb gradient is established.", "Report the encounter to ATC as soon as possible."],
        explanation: "The source closes the escape sequence only after positive climb is established.",
        sources: [src("Windshear", "18-40")],
      },
    ],
    debrief: ["Did you protect flight path rather than chase airspeed?", "Was configuration left untouched in the shear?", "Were PM callouts specific and directive?"],
  },
  {
    id: "pilot-incapacitation",
    title: "Pilot incapacitation",
    category: "Crew / operational emergency",
    phase: "Any phase",
    difficulty: "core",
    minutes: 5,
    summary: "Recognize non-response early, take control, recover the flight path and use all available automation/crew resources.",
    setup: "A crewmember becomes unresponsive or fails to correct a significant deviation.",
    objectives: ["Apply the two-communication recognition rule", "Make a positive control takeover", "Use automation and available assistance"],
    boundaryNote: boundary,
    stages: [
      {
        id: "recognition",
        label: "Recognize",
        prompt: "What is FlightSafety's Two Communication Rule?",
        expectedResponse: ["Treat failure to respond to two verbal communications as a recognition trigger, or failure to respond to one communication plus a 'Correcting' call for a significant deviation."],
        explanation: "The technique is intended to detect subtle as well as obvious incapacitation early.",
        sources: [src("Pilot Incapacitation", "18-40")],
      },
      {
        id: "control",
        label: "Take control",
        prompt: "What does the remaining pilot do first?",
        expectedResponse: ["Immediately take over the controls and recover the aircraft back on profile if required."],
        explanation: "Flight path control takes precedence over diagnosis of the incapacitated crewmember.",
        sources: [src("Pilot Incapacitation", "18-40")],
      },
      {
        id: "continue",
        label: "Manage the situation",
        prompt: "What resources/actions does the source recommend next?",
        expectedResponse: ["Declare an emergency if conditions warrant.", "If already established on approach and conditions warrant, conduct a missed approach.", "Use available resources such as autopilot and assistance from other crewmembers."],
        explanation: "The remaining pilot should reduce workload and create time/margin for the single-pilot emergency.",
        sources: [src("Pilot Incapacitation", "18-40")],
      },
    ],
    debrief: ["Was incapacitation recognized promptly?", "Was control transfer explicit?", "Did you use automation/resources to reduce workload?"],
  },
];

export const learjet3536ExpandedAbnormal: AircraftAbnormalEmergencyContent = {
  ...learjet3536NativeAbnormal,
  title: "Learjet 35/36 Abnormal, Emergency & Upset Training Reference",
  sourceNote: `${learjet3536NativeAbnormal.sourceNote} Chapter 18 maneuver/emergency profiles for emergency descent, unusual attitudes, stalls, windshear and pilot incapacitation are also represented explicitly.`,
  scenarios: [...learjet3536NativeAbnormal.scenarios, ...extraScenarios],
};
