import type {
  AircraftChecklistContent,
  AircraftLimitationsContent,
  AircraftPerformanceContent,
  AircraftProcedureContent,
  AircraftSystemsContent,
  TrainingSourceReference,
  UniversalTrainingContentDomain,
} from "./universal-aircraft-content.ts";

const AIRCRAFT_ID = "learjet-35-36";
const FSI_MANUAL_ID = "fsi-learjet-35-36-ptm-r1-1";

const source = (chapter: number, section: string, pageLabel: string): TrainingSourceReference => ({
  manualId: FSI_MANUAL_ID,
  chapter: String(chapter),
  section,
  pageLabel,
});

const authorityDisclaimer =
  "Training/familiarization content only. The applicable AFM, approved supplements, operator SOPs and regulatory publications remain controlling and take precedence if they differ from this training material.";

export const learjet3536NativeChecklists: AircraftChecklistContent = {
  aircraftId: AIRCRAFT_ID,
  title: "Learjet 35/36 Normal Flight Training Checklist",
  estimatedMinutes: 75,
  sourceNote: "Native M9 checklist derived from the FlightSafety Learjet 35/36 Pilot Training Manual, especially Chapters 2, 7, 12 and 18.",
  disclaimer: authorityDisclaimer,
  phases: [
    {
      id: "power-up",
      title: "Power up / Before start",
      sequence: 10,
      items: [
        {
          id: "batteries-on",
          challenge: "BAT 1 and BAT 2",
          response: "ON",
          procedureId: "power-up",
          explanation: "Connect both aircraft batteries to the battery-charging bus.",
          sources: [source(2, "DC Power — Batteries / Controls", "2-3")],
        },
        {
          id: "emer-power-on",
          challenge: "Emergency power",
          response: "ON",
          procedureId: "power-up",
          explanation: "The training manual describes ON as the normal position for the emergency power system.",
          sources: [source(2, "Emergency Battery", "2-19–2-20")],
        },
        {
          id: "inverters-on",
          challenge: "Primary and secondary inverters",
          response: "ON",
          procedureId: "power-up",
          explanation: "Both inverters normally operate in parallel to supply AC equipment.",
          sources: [source(2, "AC Power — Inverters", "2-15")],
        },
        {
          id: "fuel-counter-reset",
          challenge: "Fuel used counter",
          response: "RESET",
          sources: [source(7, "Fuel Flow", "7-13")],
        },
        {
          id: "pressurization-setup",
          challenge: "Pressurization",
          response: "AUTO / cruise altitude and rate SET",
          procedureId: "pressurization-setup",
          verification: "Expected cruise altitude is selected and the rate control is set for the intended cabin rate.",
          sources: [source(12, "Normal System Operation — Before Takeoff", "12-8")],
        },
      ],
    },
    {
      id: "engine-start",
      title: "Engine start",
      sequence: 20,
      items: [
        {
          id: "start-switch",
          challenge: "Selected engine GEN–OFF–START",
          response: "START",
          procedureId: "engine-start",
          explanation: "START powers the starter and automatically energizes the associated standby fuel pump and arms ignition.",
          sources: [source(7, "Other Start Functions", "7-20")],
        },
        {
          id: "throttle-idle",
          challenge: "Selected thrust lever",
          response: "CUT-OFF to IDLE",
          procedureId: "engine-start",
          explanation: "Moving the thrust lever to IDLE during START activates automatic ignition.",
          sources: [source(7, "Ignition — Automatic Mode", "7-14")],
        },
        {
          id: "monitor-start",
          challenge: "N2 and ITT",
          response: "MONITOR",
          procedureId: "engine-start",
          verification: "Engine indications show a normal acceleration toward idle without an abnormal temperature rise.",
          sources: [source(7, "Engine Instrumentation", "7-21")],
        },
        {
          id: "starter-release",
          challenge: "At applicable N2 threshold",
          response: "STARTER / IGNITION RELEASE CONFIRM",
          procedureId: "engine-start",
          explanation: "With the fuel computer on, automatic start termination occurs at the applicable approximately 45–50% N2 threshold depending on configuration.",
          sources: [source(7, "Other Start Functions", "7-20")],
        },
        {
          id: "generator-on",
          challenge: "At stable idle",
          response: "GEN",
          procedureId: "engine-start",
          sources: [source(7, "Other Start Functions", "7-20")],
        },
        {
          id: "repeat-start",
          challenge: "Other engine",
          response: "START SEQUENCE REPEAT",
          procedureId: "engine-start",
          sources: [source(7, "Starting System", "7-16–7-20")],
        },
      ],
    },
    {
      id: "taxi",
      title: "Before taxi / Taxi",
      sequence: 30,
      items: [
        {
          id: "electrical-check",
          challenge: "Generators and electrical indications",
          response: "CHECK",
          verification: "Normal generating sources are available and indications are normal.",
          sources: [source(2, "Generators", "2-5–2-6")],
        },
        {
          id: "taxi-route",
          challenge: "Taxi route",
          response: "REVIEW",
          explanation: "Verify the taxi clearance against the airport diagram.",
          sources: [source(18, "Taxi Procedures", "18-13")],
        },
        {
          id: "taxi-checklist",
          challenge: "Taxi checklist",
          response: "COMPLETE",
          sources: [source(18, "Taxi Procedures", "18-13")],
        },
      ],
    },
    {
      id: "before-takeoff",
      title: "Before takeoff / Line-up",
      sequence: 40,
      items: [
        {
          id: "air-ignition-on",
          challenge: "L and R AIR IGN",
          response: "ON",
          explanation: "Selective air ignition is used for takeoff and landing in the training profile.",
          sources: [source(7, "Ignition — Selective Mode", "7-14")],
        },
        {
          id: "takeoff-speeds",
          challenge: "V1, VR, V2 and V2+30",
          response: "SET / BUGGED",
          procedureId: "takeoff",
          sources: [source(18, "Takeoff Setup / Standard Callouts", "18-8–18-9")],
        },
        {
          id: "toga-fd",
          challenge: "TOGA / flight director takeoff setup",
          response: "SET",
          procedureId: "takeoff",
          sources: [source(18, "Takeoff Setup", "18-8")],
        },
        {
          id: "lineup-check",
          challenge: "Runway line-up checklist",
          response: "COMPLETE",
          sources: [source(18, "Takeoff Procedures", "18-13")],
        },
      ],
    },
    {
      id: "takeoff",
      title: "Takeoff",
      sequence: 50,
      items: [
        { id: "set-power", challenge: "Takeoff power", response: "SET", procedureId: "takeoff", sources: [source(18, "Takeoff Procedures", "18-13")] },
        { id: "airspeed-alive", challenge: "Initial airspeed", response: "CROSS-CHECK", procedureId: "takeoff", sources: [source(18, "Takeoff Procedures", "18-13")] },
        { id: "eighty", challenge: "80 kt", response: "CROSS-CHECK", procedureId: "takeoff", sources: [source(18, "Standard Callouts", "18-9")] },
        { id: "rotate", challenge: "At VR", response: "ROTATE", procedureId: "takeoff", sources: [source(18, "Takeoff Procedures", "18-13")] },
        { id: "positive-rate", challenge: "Positive rate", response: "GEAR UP / YAW DAMPER ON", procedureId: "takeoff", sources: [source(18, "Takeoff Procedures", "18-13")] },
        { id: "flaps-up", challenge: "At V2 + 30", response: "FLAPS UP / AFTER TAKEOFF CHECK", procedureId: "takeoff", sources: [source(18, "Takeoff Procedures", "18-13")] },
      ],
    },
    {
      id: "climb-cruise",
      title: "Climb / Cruise",
      sequence: 60,
      items: [
        { id: "climb-checklist", challenge: "Transition altitude", response: "STANDARD PRESSURE / CLIMB CHECK", sources: [source(18, "Standard Callouts", "18-9")] },
        { id: "cruise-checklist", challenge: "Cruise established", response: "CRUISE CHECK", sources: [source(18, "Standard Callouts", "18-10")] },
      ],
    },
    {
      id: "descent-approach",
      title: "Descent / Approach",
      sequence: 70,
      items: [
        { id: "descent-checklist", challenge: "Beginning of descent", response: "DESCENT CHECK", procedureId: "descent-approach", sources: [source(18, "Standard Callouts", "18-10")] },
        { id: "approach-brief", challenge: "Approach", response: "SETUP / BRIEF / APPROACH CHECK", procedureId: "descent-approach", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "flaps-20", challenge: "Below applicable speed", response: "FLAPS 20°", procedureId: "descent-approach", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "gear-down", challenge: "Landing gear", response: "DOWN / THREE GREEN", procedureId: "descent-approach", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "before-landing", challenge: "Before Landing checklist", response: "COMPLETE", procedureId: "descent-approach", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "full-flaps", challenge: "Below 150 kt when required", response: "FULL FLAPS", procedureId: "descent-approach", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
      ],
    },
    {
      id: "landing",
      title: "Landing / After landing",
      sequence: 80,
      items: [
        { id: "landing-air-ign", challenge: "L and R AIR IGN", response: "ON CONFIRM", sources: [source(7, "Ignition — Selective Mode", "7-14")] },
        { id: "sixty-knots", challenge: "Landing rollout", response: "60 KT CALLOUT", sources: [source(18, "Standard Callouts — Landing", "18-12")] },
        { id: "after-landing-check", challenge: "Clear of runway", response: "AFTER LANDING CHECK", sources: [source(18, "Checklist Procedures", "18-4")] },
      ],
    },
    {
      id: "shutdown",
      title: "Shutdown / Secure",
      sequence: 90,
      items: [
        { id: "shutdown-checklist", challenge: "Shutdown checklist", response: "COMPLETE", procedureId: "shutdown", sources: [source(18, "Checklist Procedures", "18-4")] },
        { id: "emer-power-off", challenge: "Emergency power", response: "OFF BEFORE LEAVING AIRCRAFT", procedureId: "shutdown", explanation: "Leaving emergency power selected after normal aircraft power is removed can discharge the emergency battery.", sources: [source(2, "Emergency Battery", "2-20")] },
        { id: "battery-hot-items", challenge: "Battery-hot-bus lights / items", response: "OFF", procedureId: "shutdown", sources: [source(2, "Distribution — Battery Hot Buses", "2-12")] },
        { id: "batteries-off", challenge: "BAT 1 and BAT 2", response: "OFF", procedureId: "shutdown", sources: [source(2, "DC Power — Batteries / Controls", "2-3")] },
      ],
    },
  ],
};

export const learjet3536NativeProcedures: AircraftProcedureContent = {
  aircraftId: AIRCRAFT_ID,
  title: "Learjet 35/36 Operating Procedures",
  sourceNote: "Procedure detail is structured from the FlightSafety Learjet 35/36 Pilot Training Manual. It supplements, but does not replace, approved aircraft and operator procedures.",
  disclaimer: authorityDisclaimer,
  procedures: [
    {
      id: "power-up",
      title: "Initial electrical power-up",
      phase: "Before start",
      summary: "Establish battery and AC power, then configure the emergency-power layer before engine start.",
      steps: [
        { id: "power-batteries", action: "Select BAT 1 and BAT 2 ON.", expectedResult: "Aircraft DC buses are energized from the batteries.", sources: [source(2, "DC Power — Batteries / Controls", "2-3")] },
        { id: "power-emergency", action: "Select emergency power ON for normal operation.", verification: "Emergency-power indications agree with the selected state.", sources: [source(2, "Emergency Battery", "2-19–2-20")] },
        { id: "power-inverters", action: "Select the required primary and secondary inverters ON.", expectedResult: "Required AC equipment has a normal AC source.", sources: [source(2, "AC Power — Inverters", "2-15")] },
      ],
      completionCriteria: ["Required DC and AC sources are available", "No unexplained electrical warning remains"],
      sources: [source(2, "Electrical Power Systems", "2-1–2-20")],
    },
    {
      id: "pressurization-setup",
      title: "Pressurization setup before takeoff",
      phase: "Before takeoff",
      summary: "Configure the automatic pressurization system for the intended flight profile before departure.",
      steps: [
        { id: "press-auto", action: "Select pressurization AUTO.", sources: [source(12, "Normal System Operation — Before Takeoff", "12-8")] },
        { id: "press-altitude", action: "Set the expected cruise altitude on the cabin controller.", verification: "Selected aircraft altitude agrees with the planned cruise altitude.", sources: [source(12, "Normal System Operation — Before Takeoff", "12-8")] },
        { id: "press-rate", action: "Set the desired cabin rate.", rationale: "The training manual describes approximately the 9 o'clock RATE position as a normal starting point, corresponding to roughly 500–600 fpm.", sources: [source(12, "Pressurization Control Module / Normal Operation", "12-4, 12-8")] },
      ],
      completionCriteria: ["AUTO selected", "Planned cruise altitude selected", "Cabin rate set"],
      sources: [source(12, "Pressurization", "12-1–12-8")],
    },
    {
      id: "engine-start",
      title: "Engine start — common training sequence",
      phase: "Engine start",
      summary: "Command starter engagement, introduce fuel/ignition with the thrust lever, monitor acceleration, and place the generator online after a stable idle.",
      steps: [
        { id: "start-command", action: "Move the selected GEN–OFF–START switch to START.", expectedResult: "Starter engages; associated start-support functions are energized.", sources: [source(7, "Other Start Functions", "7-20")] },
        { id: "start-fuel", action: "Move the selected thrust lever from CUT-OFF to IDLE during the start.", expectedResult: "Automatic ignition is activated and the engine accelerates.", sources: [source(7, "Ignition — Automatic Mode", "7-14")] },
        { id: "start-monitor", action: "Monitor N2 and ITT throughout the start; cross-check the other engine indications.", verification: "Indications progress normally toward idle without an abnormal temperature or acceleration trend.", sources: [source(7, "Engine Instrumentation", "7-21")] },
        { id: "start-release", action: "Confirm automatic starter/ignition release near the applicable approximately 45–50% N2 threshold.", rationale: "The exact threshold depends on configuration/fuel-computer installation.", sources: [source(7, "Other Start Functions", "7-20")] },
        { id: "start-gen", action: "After a stable idle, select GEN as appropriate.", verification: "Generator output and electrical indications are normal.", sources: [source(7, "Other Start Functions", "7-20"), source(2, "Generators", "2-5–2-6")] },
      ],
      completionCriteria: ["Engine is stable at idle", "Starter/ignition have released", "Generator output is normal"],
      sources: [source(7, "Starting System", "7-16–7-21")],
    },
    {
      id: "takeoff",
      title: "Normal takeoff training profile",
      phase: "Takeoff",
      prerequisites: ["Takeoff performance and V-speeds determined from the applicable approved data", "Before-takeoff checks complete"],
      steps: [
        { id: "to-power", action: "Set takeoff power and cross-check engine indications.", sources: [source(18, "Takeoff Procedures", "18-13")] },
        { id: "to-speed", action: "Cross-check initial airspeed indications and the 80-knot callout.", sources: [source(18, "Standard Callouts / Takeoff Procedures", "18-9, 18-13")] },
        { id: "to-rotate", action: "At VR, rotate to the takeoff attitude.", expectedResult: "Aircraft lifts off on the planned takeoff profile.", sources: [source(18, "Takeoff Procedures", "18-13")] },
        { id: "to-gear", action: "With positive rate, retract the landing gear and engage the yaw damper as directed by the profile.", verification: "Gear retracts and the selected yaw damper is engaged.", sources: [source(18, "Takeoff Procedures", "18-13")] },
        { id: "to-flaps", action: "At V2 + 30, retract flaps and complete the after-takeoff check.", sources: [source(18, "Takeoff Procedures", "18-13")] },
      ],
      completionCriteria: ["Aircraft clean and climbing", "After-takeoff check complete"],
      sources: [source(18, "Takeoff Setup / Standard Callouts / Takeoff Procedures", "18-8–18-13")],
    },
    {
      id: "descent-approach",
      title: "Descent and normal approach setup",
      phase: "Descent / Approach",
      steps: [
        { id: "app-descent", action: "At the beginning of descent, complete the descent check.", sources: [source(18, "Standard Callouts", "18-10")] },
        { id: "app-brief", action: "Set up and brief the approach, then complete the approach check.", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "app-flaps20", action: "Below the applicable flap speed, select 20° flaps when required by the approach profile.", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "app-gear", action: "Select landing gear DOWN and verify three green indications.", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "app-beforelanding", action: "Complete the Before Landing check.", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
        { id: "app-fullflaps", action: "Below 150 kt, select full flaps when required for the approach.", sources: [source(18, "Standard Callouts — Approach", "18-11")] },
      ],
      completionCriteria: ["Landing configuration agrees with the selected approach", "Before Landing check complete"],
      sources: [source(18, "Standard Callouts — Approach", "18-11")],
    },
    {
      id: "go-around",
      title: "Go-around / Balked landing training profile",
      phase: "Approach / Landing",
      summary: "FlightSafety recommends the flight-director go-around mode where applicable to provide an approximately 9° nose-up command; FC-200 autopilot disengagement differs.",
      steps: [
        { id: "ga-initial", action: "Disengage the autopilot as applicable, establish approximately 9° nose-up and set takeoff power or power as required.", verification: "Spoilers are retracted.", sources: [source(18, "Go-Around / Balked Landing", "18-35")] },
        { id: "ga-flaps20", action: "At or above VREF, select/confirm flaps 20°.", sources: [source(18, "Go-Around / Balked Landing", "18-35")] },
        { id: "ga-gear", action: "With positive rate, retract the landing gear and engage the yaw damper.", sources: [source(18, "Go-Around / Balked Landing", "18-35")] },
        { id: "ga-climb", action: "Accelerate toward approach-climb speed (approximately VREF + 7 kt).", sources: [source(18, "Go-Around / Balked Landing", "18-35")] },
        { id: "ga-clean", action: "Clear of obstacles, accelerate to VREF + 30 kt and retract the flaps.", sources: [source(18, "Go-Around / Balked Landing", "18-35")] },
      ],
      sources: [source(18, "Go-Around / Balked Landing", "18-35")],
    },
    {
      id: "shutdown",
      title: "Shutdown and secure",
      phase: "Shutdown",
      steps: [
        { id: "sd-check", action: "Complete the normal shutdown checklist sequence.", sources: [source(18, "Checklist Procedures", "18-4")] },
        { id: "sd-emergency", action: "Select emergency power OFF before leaving the aircraft.", rationale: "Emergency battery discharge can occur if the system remains selected after normal aircraft power is removed.", sources: [source(2, "Emergency Battery", "2-20")] },
        { id: "sd-hotbus", action: "Confirm battery-hot-bus lights/equipment are OFF as appropriate.", rationale: "Battery-hot-bus loads can remain energized with normal aircraft power removed.", sources: [source(2, "Distribution — Battery Hot Buses", "2-12")] },
        { id: "sd-batteries", action: "Select BAT 1 and BAT 2 OFF when securing the aircraft.", sources: [source(2, "DC Power — Batteries / Controls", "2-3")] },
      ],
      completionCriteria: ["Aircraft electrical sources secured", "No unintended battery-hot-bus load remains"],
      sources: [source(18, "Checklist Procedures", "18-4"), source(2, "Electrical Power Systems", "2-1–2-20")],
    },
  ],
};

export const learjet3536NativePerformance: AircraftPerformanceContent = {
  aircraftId: AIRCRAFT_ID,
  title: "Learjet 35/36 Performance Training Reference",
  sourceNote: "Structured from FlightSafety Chapters 18–20. Values are training-reference data and are not a dispatch substitute for the applicable AFM performance charts.",
  disclaimer: authorityDisclaimer,
  datasets: [
    {
      id: "certified-takeoff-weight",
      title: "Maximum certified takeoff weight by configuration",
      description: "Training-manual structural/certification reference. Actual allowable takeoff weight is the most restrictive applicable certified, climb/brake-energy, runway/ambient and obstacle-clearance limit.",
      kind: "reference-table",
      axes: [{ key: "configuration", label: "Configuration", values: ["35/36 standard", "35/36 AAK 77-8", "35/36 AAK 80-2", "36/36A standard", "36/36A AAK 80-2"] }],
      outputs: [{ key: "maxTakeoffWeight", label: "Maximum certified takeoff weight", unit: "lb" }],
      rows: [
        { inputs: { configuration: "35/36 standard" }, outputs: { maxTakeoffWeight: 17000 } },
        { inputs: { configuration: "35/36 AAK 77-8" }, outputs: { maxTakeoffWeight: 18000 } },
        { inputs: { configuration: "35/36 AAK 80-2" }, outputs: { maxTakeoffWeight: 18300 } },
        { inputs: { configuration: "36/36A standard" }, outputs: { maxTakeoffWeight: 18000 } },
        { inputs: { configuration: "36/36A AAK 80-2" }, outputs: { maxTakeoffWeight: 18300 } },
      ],
      interpolation: "none",
      notes: ["Takeoff may use 8° or 20° flaps; the training manual states contaminated-runway takeoff requires 20° flaps."],
      sources: [source(20, "Maximum Allowable / Maximum Certified Takeoff Weight", "20-6–20-7")],
    },
    {
      id: "weight-envelope-configurations",
      title: "Ramp, takeoff and zero wing/tip fuel structural weights",
      description: "The Learjet 35/36 weight envelope changes with incorporated engineering changes/modification kits. Do not apply a higher configuration limit to an aircraft that does not have that configuration.",
      kind: "reference-table",
      axes: [{ key: "configuration", label: "Configuration", values: ["Model 35 — no ECR 1495 / AAK 77-8 / AAK 80-2", "Model 35 ECR 1495 or AAK 77-8 / Model 36 without AAK 80-2", "Model 35 or 36 incorporating AAK 80-2"] }],
      outputs: [
        { key: "maxRampWeight", label: "Max ramp weight", unit: "lb" },
        { key: "maxTakeoffWeight", label: "Max takeoff weight", unit: "lb" },
        { key: "maxZeroWingTipFuel", label: "Max zero wing & tip fuel weight", unit: "lb" },
      ],
      rows: [
        { inputs: { configuration: "Model 35 — no ECR 1495 / AAK 77-8 / AAK 80-2" }, outputs: { maxRampWeight: 17250, maxTakeoffWeight: 17000, maxZeroWingTipFuel: 13500 } },
        { inputs: { configuration: "Model 35 ECR 1495 or AAK 77-8 / Model 36 without AAK 80-2" }, outputs: { maxRampWeight: 18250, maxTakeoffWeight: 18000, maxZeroWingTipFuel: 13500 } },
        { inputs: { configuration: "Model 35 or 36 incorporating AAK 80-2" }, outputs: { maxRampWeight: 18500, maxTakeoffWeight: 18300, maxZeroWingTipFuel: 13500 } },
      ],
      interpolation: "none",
      sources: [source(19, "CG envelopes / structural weights", "19-2–19-4")],
    },
    {
      id: "certified-landing-weight",
      title: "Maximum certified landing weight",
      description: "The actual maximum allowable landing weight is the lowest applicable structural, airport/temperature and runway/ambient performance limit.",
      kind: "reference-table",
      axes: [{ key: "configuration", label: "Configuration", values: ["35/36 standard", "35/36 AAK 80-3", "35A/36A standard", "35A/36A AAK 80-3"] }],
      outputs: [{ key: "maxLandingWeight", label: "Maximum certified landing weight", unit: "lb" }],
      rows: [
        { inputs: { configuration: "35/36 standard" }, outputs: { maxLandingWeight: 14300 } },
        { inputs: { configuration: "35/36 AAK 80-3" }, outputs: { maxLandingWeight: 15300 } },
        { inputs: { configuration: "35A/36A standard" }, outputs: { maxLandingWeight: 14300 } },
        { inputs: { configuration: "35A/36A AAK 80-3" }, outputs: { maxLandingWeight: 15300 } },
      ],
      interpolation: "none",
      sources: [source(20, "Maximum Allowable / Maximum Certified Landing Weight", "20-31")],
    },
    {
      id: "takeoff-climb-segments",
      title: "Takeoff and landing climb-gradient training requirements",
      kind: "reference-table",
      axes: [{ key: "segment", label: "Segment", values: ["First segment", "Second segment", "Final segment", "Approach climb", "Landing climb"] }],
      outputs: [{ key: "grossGradient", label: "Gross climb-gradient requirement" }],
      rows: [
        { inputs: { segment: "First segment" }, outputs: { grossGradient: "Positive" } },
        { inputs: { segment: "Second segment" }, outputs: { grossGradient: "≥ 2.4%" } },
        { inputs: { segment: "Final segment" }, outputs: { grossGradient: "≥ 1.2%" } },
        { inputs: { segment: "Approach climb" }, outputs: { grossGradient: "≥ 2.1%" } },
        { inputs: { segment: "Landing climb" }, outputs: { grossGradient: "≥ 3.2%" } },
      ],
      interpolation: "none",
      notes: ["These values describe the certification/performance chart logic in the training manual; use the applicable AFM chart for flight planning."],
      sources: [source(20, "Climb Segments", "20-6–20-7"), source(20, "Approach and Landing", "20-31")],
    },
    {
      id: "single-engine-drift-down",
      title: "Single-engine drift-down speed schedule",
      description: "Training profile for maximum-distance drift-down after an engine failure at high altitude; the same schedule approximates best single-engine rate-of-climb speed below the single-engine service ceiling.",
      kind: "reference-table",
      axes: [{ key: "segment", label: "Segment", values: ["Initial", "High-altitude descent", "Mach transition", "Lower descent"] }],
      outputs: [{ key: "target", label: "Training target" }],
      rows: [
        { inputs: { segment: "Initial" }, outputs: { target: "Maximum continuous thrust; maintain altitude until 170 KIAS" } },
        { inputs: { segment: "High-altitude descent" }, outputs: { target: "170 KIAS until reaching M 0.50" } },
        { inputs: { segment: "Mach transition" }, outputs: { target: "M 0.50 until reaching 200 KIAS" } },
        { inputs: { segment: "Lower descent" }, outputs: { target: "200 KIAS to single-engine cruise altitude" } },
      ],
      interpolation: "none",
      sources: [source(18, "Single-Engine Drift Down", "18-36")],
    },
  ],
};

export const learjet3536NativeLimitations: AircraftLimitationsContent = {
  aircraftId: AIRCRAFT_ID,
  title: "Learjet 35/36 Limitations Training Reference",
  sourceNote: "Only limitations/configuration facts directly supported by the registered FlightSafety training manual are included here. Configuration-specific AFM data remains controlling.",
  disclaimer: authorityDisclaimer,
  groups: [
    {
      id: "weight-altitude",
      title: "Weight and altitude",
      items: [
        { id: "max-operating-altitude", label: "Maximum operating altitude", value: 45000, unit: "ft", sources: [source(1, "Aircraft General — General", "1-1")] },
        { id: "max-zero-wing-tip-fuel", label: "Maximum zero wing and tip fuel weight", value: 13500, unit: "lb", condition: "Shown across the Chapter 19 Learjet 35/36 CG envelopes.", sources: [source(19, "CG envelopes", "19-2–19-4")] },
        { id: "max-takeoff-standard-35", label: "Maximum certified takeoff weight — 35/36 standard", value: 17000, unit: "lb", condition: "Higher limits require the applicable modification/configuration.", sources: [source(20, "Maximum Certified Takeoff Weight", "20-6")] },
        { id: "max-takeoff-aak77", label: "Maximum certified takeoff weight — AAK 77-8", value: 18000, unit: "lb", sources: [source(20, "Maximum Certified Takeoff Weight", "20-6")] },
        { id: "max-takeoff-aak80-2", label: "Maximum certified takeoff weight — AAK 80-2", value: 18300, unit: "lb", sources: [source(20, "Maximum Certified Takeoff Weight", "20-6")] },
      ],
      sources: [source(19, "Weight and Balance", "19-2–19-4"), source(20, "Takeoff Performance", "20-6")],
    },
    {
      id: "landing-weight",
      title: "Landing weight",
      items: [
        { id: "max-landing-standard", label: "Maximum certified landing weight — standard", value: 14300, unit: "lb", condition: "Training manual lists this structural limit for standard 35/36 and 35A/36A configurations.", sources: [source(20, "Maximum Certified Landing Weight", "20-31")] },
        { id: "max-landing-aak80-3", label: "Maximum certified landing weight — AAK 80-3", value: 15300, unit: "lb", condition: "Applies only when the corresponding AAK 80-3 configuration is incorporated.", sources: [source(20, "Maximum Certified Landing Weight", "20-31")] },
        { id: "landing-lowest-limit", label: "Allowable landing weight", value: "Lowest applicable limit", condition: "Use the lowest of the structural maximum, airport altitude/temperature landing-weight limit and runway/ambient landing-distance limit.", notices: [{ kind: "warning", text: "Do not use the structural maximum alone as the dispatch landing limit." }], sources: [source(20, "Maximum Allowable Landing Weight", "20-31")] },
      ],
      sources: [source(20, "Approach and Landing", "20-31")],
    },
    {
      id: "takeoff-configuration",
      title: "Takeoff configuration / performance boundary",
      items: [
        { id: "takeoff-flap-options", label: "Normal takeoff flap settings covered", value: "8° or 20°", sources: [source(20, "Takeoff — Climb Segment Configurations", "20-6")] },
        { id: "contaminated-takeoff", label: "Contaminated-runway takeoff", value: "20° flaps", condition: "The training manual specifies 20° flaps for contaminated-runway takeoff.", sources: [source(20, "Takeoff — Climb Segment Configurations", "20-6")] },
        { id: "takeoff-lowest-limit", label: "Allowable takeoff weight", value: "Most restrictive applicable limit", condition: "Certified weight, climb/brake-energy weight limit, runway/ambient takeoff distance and obstacle-clearance requirements all constrain allowable takeoff weight.", notices: [{ kind: "warning", text: "Determine takeoff weight from the applicable approved performance data for the aircraft and conditions." }], sources: [source(20, "Maximum Allowable Takeoff Weight", "20-6")] },
      ],
      sources: [source(20, "Takeoff Performance", "20-6–20-7")],
    },
  ],
};

export const learjet3536NativeSystems: AircraftSystemsContent = {
  aircraftId: AIRCRAFT_ID,
  title: "Learjet 35/36 Essential Systems",
  sourceNote: "Pilot-facing mental models migrated into the native M9 systems domain from the registered FlightSafety manual.",
  disclaimer: authorityDisclaimer,
  systems: [
    {
      id: "electrical",
      title: "Electrical",
      summary: "Two engine-driven generators are the normal DC sources; batteries support starting/secondary power and static inverters create AC from DC.",
      mentalModel: "Learn the sources and normal power path first. Bus architecture and emergency-power details vary with serial number and modification status.",
      components: ["Two engine-driven DC generators", "Aircraft batteries", "Primary and secondary static inverters", "Emergency-battery layer"],
      controls: ["BAT switches", "GEN–OFF–START switches", "Primary / secondary inverter switches"],
      indications: ["Generator availability/load", "DC voltage", "Battery and emergency-power indications as fitted"],
      normalOperation: ["Both normal generating sources available after start", "Required inverters operating", "No unexplained generator/emergency-power warning"],
      remember: ["Each generator is rated 30 V / 400 A in the training manual.", "One generator can sustain the normal DC load."],
      applicability: { note: "Bus architecture and emergency-battery installation vary by serial number/modification status." },
      sources: [source(2, "Electrical Power Systems — Introduction / Generators", "2-1, 2-5")],
    },
    {
      id: "fuel",
      title: "Fuel",
      summary: "Engines are supplied from the wing system while tip and fuselage fuel are managed through transfer logic.",
      mentalModel: "Think wing-fed engines plus deliberate tip/fuselage transfer management, not one generic tank.",
      components: ["Wing tanks", "Tip tanks", "Fuselage tank where installed", "Jet pumps", "Electric standby pumps"],
      controls: ["Standby pump switches", "XFER–FILL", "Fuselage valve / crossflow controls as fitted"],
      indications: ["Fuel quantity by tank group", "Transfer/valve indications", "Fuel balance"],
      normalOperation: ["Engines supplied from the wing system", "Transfer performed deliberately", "Selected transfer mode agrees with indications"],
      remember: ["Training-manual usable fuel is approximately 6,238 lb on the 35 and 7,440 lb on the 36.", "Fuel architecture and transfer details differ across models and serial numbers."],
      sources: [source(5, "Fuel Tanks / Boost Pumps / Transfer", "5-3, 5-8, 5-12")],
    },
    {
      id: "powerplant",
      title: "Powerplant & Start",
      summary: "Two TFE731-2-2B turbofan engines use an assisted start sequence in which the pilot commands START, introduces fuel at IDLE and monitors acceleration.",
      mentalModel: "Your main task during start is command, monitor and verify; do not memorize relay logic before learning the engine indications.",
      controls: ["GEN–OFF–START", "Thrust levers CUT-OFF / IDLE", "Air ignition selections"],
      indications: ["N2", "ITT", "N1", "Starter/ignition indications as fitted"],
      normalOperation: ["N2 increases after starter engagement", "Fuel/ignition introduced at IDLE", "Starter/ignition release at the applicable threshold", "Stable idle before generator selection"],
      remember: ["Primary start indications are N2, ITT and N1.", "Starter release is approximately 45% or 50% N2 depending on configuration/fuel-computer installation."],
      sources: [source(7, "Powerplant / Starting System / Engine Instrumentation", "7-1, 7-14, 7-20–7-21")],
    },
    {
      id: "hydraulics",
      title: "Hydraulics",
      summary: "Two engine-driven pumps provide main hydraulic pressure and an electric auxiliary pump provides backup capability for selected functions.",
      mentalModel: "Hydraulics move high-force secondary systems; the primary aileron/elevator/rudder controls themselves are mechanical.",
      components: ["Two engine-driven pumps", "Reservoir", "Auxiliary electric pump"],
      controls: ["Auxiliary hydraulic pump", "Gear, flap, spoiler and brake subsystem controls"],
      indications: ["Hydraulic pressure", "Position/status of commanded hydraulic consumers"],
      normalOperation: ["Main pressure approximately 1,550 psi", "Hydraulic consumers respond normally"],
      remember: ["Hydraulics power landing gear, flaps, spoilers/spoilerons, brakes and optional thrust reversers.", "Auxiliary-pump capability is not identical to main-system capability."],
      sources: [source(13, "Hydraulic Power System — General", "13-1")],
    },
    {
      id: "pneumatics",
      title: "Pneumatics / Bleed Air",
      summary: "Engine compressor bleed air is distributed as a shared pneumatic resource for multiple aircraft systems.",
      mentalModel: "A bleed-air problem can affect several downstream systems at once: pressurization, conditioning, anti-ice and hydraulic-reservoir pressurization.",
      controls: ["L / R BLEED AIR switches", "Emergency bleed/pressurization selections where fitted"],
      indications: ["Bleed-air warning indications", "Downstream cabin/anti-ice response"],
      normalOperation: ["Bleed sources selected for the phase", "No bleed warning", "Normal downstream response"],
      remember: ["Low-pressure bleed can be supplemented by high-pressure air when required."],
      applicability: { note: "Valve logic and emergency-pressurization architecture differ between early and later aircraft." },
      sources: [source(9, "Pneumatics — Introduction / Bleed Air Switches", "9-1, 9-4")],
    },
    {
      id: "pressurization",
      title: "Pressurization",
      summary: "Bleed air enters the cabin and the outflow valve meters air leaving; AUTO regulates cabin pressure toward the selected aircraft-altitude schedule.",
      mentalModel: "Normal pressurization is primarily an outflow-control problem: set the intended flight profile and monitor cabin altitude, rate and differential pressure.",
      controls: ["AUTO–MAN", "Aircraft-altitude/cabin controller", "RATE", "Manual UP–DN control if required"],
      indications: ["Cabin altitude", "Differential pressure", "Cabin rate / warnings"],
      normalOperation: ["AUTO selected", "Expected cruise altitude set before takeoff", "Desired cabin rate selected"],
      remember: ["The training manual describes approximately the 9 o'clock RATE position as roughly 500–600 fpm.", "Current-model normal differential is described around 9.2 psid; configuration must be verified."],
      applicability: { note: "System limits and automatic protection vary between early and current aircraft." },
      sources: [source(12, "Pressurization — Introduction / Control Module / Normal Operation", "12-1, 12-4, 12-8")],
    },
    {
      id: "flight-controls",
      title: "Flight Controls",
      summary: "Primary aileron, elevator and rudder control is mechanical; trim is electrical, while flaps and spoilers/spoilerons are electrically controlled and hydraulically actuated.",
      mentalModel: "Separate primary manual control paths from the powered secondary surfaces.",
      controls: ["Control wheel/column/pedals", "Electrical trim", "Flaps", "Spoilers", "Yaw damper"],
      indications: ["Trim position", "Flap/spoiler indication", "Yaw-damper status"],
      normalOperation: ["Primary controls free", "Correct trim", "Secondary surfaces agree with command", "Required yaw damper engaged in flight"],
      remember: ["Primary controls do not use hydraulic boost.", "One yaw damper is intended for inflight operation in the training material."],
      sources: [source(15, "Flight Controls — General / Yaw Damper", "15-1, 15-23")],
    },
    {
      id: "anti-ice",
      title: "Ice and Rain Protection",
      summary: "Protection is distributed across electrical heat, engine bleed air and alcohol systems depending on the surface/component.",
      mentalModel: "Think by protected surface and energy source rather than looking for one universal anti-ice master system.",
      controls: ["Pitot/static and sensor heat", "Engine/wing/stabilizer anti-ice", "Windshield/radome protection as fitted"],
      indications: ["Anti-ice warning/temperature indications as fitted", "Visible ice", "Bleed-air response"],
      normalOperation: ["Required protection selected for conditions", "Protected systems respond normally"],
      remember: ["Exact anti-ice architecture is configuration-dependent."],
      applicability: { note: "Windshield and other protection installations vary by serial number/modification status." },
      sources: [source(10, "Ice and Rain Protection — Introduction", "10-1")],
    },
    {
      id: "landing-gear-brakes",
      title: "Landing Gear & Brakes",
      summary: "Landing gear is electrically controlled and hydraulically operated; alternate extension and emergency braking use pneumatic capability.",
      mentalModel: "Normal gear/braking is hydraulic, but the emergency layer is pneumatic. Nosewheel steering is electrical.",
      controls: ["Landing gear selector", "Brakes / antiskid", "Nosewheel steering", "Alternate/emergency controls when required"],
      indications: ["Gear position / unsafe indications", "Hydraulic pressure", "Brake/antiskid status"],
      normalOperation: ["Commanded gear position agrees with indications", "Normal braking and antiskid available", "Nosewheel steering responds normally"],
      remember: ["Alternate gear extension and emergency braking do not use the normal hydraulic path."],
      sources: [source(14, "Landing Gear and Brakes — Introduction", "14-1")],
    },
  ],
};

export type StaticUniversalTrainingModule = {
  readonly aircraftId: string;
  readonly domain: UniversalTrainingContentDomain;
  readonly payload: { readonly aircraftId: string };
};

export const learjet3536NativeModules: readonly StaticUniversalTrainingModule[] = [
  { aircraftId: AIRCRAFT_ID, domain: "checklists", payload: learjet3536NativeChecklists },
  { aircraftId: AIRCRAFT_ID, domain: "procedures", payload: learjet3536NativeProcedures },
  { aircraftId: AIRCRAFT_ID, domain: "performance", payload: learjet3536NativePerformance },
  { aircraftId: AIRCRAFT_ID, domain: "limitations", payload: learjet3536NativeLimitations },
  { aircraftId: AIRCRAFT_ID, domain: "systems", payload: learjet3536NativeSystems },
];
