import type { AircraftChecklistContent, AircraftChecklistItem, TrainingSourceReference } from "./universal-aircraft-content.ts";

const AIRCRAFT_ID = "learjet-35-36";
export const CAE_LEARJET_CRH_ID = "cae-simuflite-learjet-35-36-crh-feb-2007";

const cae = (section: string, pageLabel: string): TrainingSourceReference => ({
  manualId: CAE_LEARJET_CRH_ID,
  section,
  pageLabel,
});

const item = (
  id: string,
  challenge: string,
  response: string,
  section: string,
  pageLabel: string,
  extra: Partial<AircraftChecklistItem> = {},
): AircraftChecklistItem => ({ id, challenge, response, sources: [cae(section, pageLabel)], ...extra });

const trainingBoundary =
  "CAE SimuFlite identifies this handbook as familiarization/training material and not a substitute for the manufacturer's Pilot or Maintenance Manuals. Applicable approved aircraft, operator and regulatory documentation remains controlling.";

/**
 * Primary practical normal-flight checklist for the Learjet workspace.
 *
 * CAE's own checklist philosophy is preserved: complete the cockpit/event flow
 * first, then use the normal checklist as a challenge-response done list. Long
 * system tests stay linked to their expanded procedures rather than turning the
 * in-flight checklist into an instruction manual.
 */
export const learjet3536CaeNormalChecklist: AircraftChecklistContent = {
  aircraftId: AIRCRAFT_ID,
  title: "CAE Learjet 35/36 Normal Procedures — Pilot Checklist",
  estimatedMinutes: 70,
  sourceNote:
    "Primary FLY checklist from CAE SimuFlite Learjet 35/36 Cockpit Reference Handbook, February 2007. CAE directs crews to perform cockpit/event flows first and use the checklist afterward as a challenge-response done list.",
  disclaimer: trainingBoundary,
  phases: [
    {
      id: "preflight-exterior",
      title: "Preflight — exterior walkaround",
      sequence: 10,
      sources: [cae("Preflight Inspection — Power Off Inspection", "2A-2–2A-13")],
      items: [
        item("pf-left-nose", "Left nose / pitot-static / stall vane / nose gear", "CHECKED", "Power Off Inspection — Left Nose", "2A-2", { explanation: "Covers discharge outlets, pitot/static sources and drains, stall vane, nose gear/wheel well, tire, doors, uplock, radome and static-discharge condition." }),
        item("pf-right-nose", "Right nose / oxygen / probes / static ports / antennas", "CHECKED", "Power Off Inspection — Right Nose", "2A-3"),
        item("pf-right-root", "Right wing root / inlet / drains / main gear", "CHECKED", "Power Off Inspection — Right Wing Root", "2A-4", { notices: [{ kind: "warning", text: "Wing, flight-control surfaces and engine inlet must be free of frost, snow and ice." }] }),
        item("pf-right-wing-forward", "Right wing forward / vents / wing configuration / heat scupper", "CHECKED", "Power Off Inspection — Right Wing Forward", "2A-5", { condition: "Inspect the installed Standard, Century III/Softflite or Mark IV configuration; do not infer wing configuration from model name." }),
        item("pf-right-tip", "Right tip tank / cap / drain / lights / jettison tube", "CHECKED", "Power Off Inspection — Right Tip Tank", "2A-6"),
        item("pf-right-wing-aft", "Right wing aft / aileron / spoiler / flap", "CHECKED", "Power Off Inspection — Right Wing Aft", "2A-6"),
        item("pf-right-nacelle", "Right nacelle / oil / exhaust / reverser / fuel drains", "CHECKED", "Power Off Inspection — Right Nacelle / Aft Lower Fuselage", "2A-7", { condition: "Thrust-reverser inspection depends on installed Aeronca or Dee Howard system." }),
        item("pf-tailcone", "Tailcone / batteries / hydraulics / fire bottles / installed equipment", "CHECKED / SECURED", "Power Off Inspection — Aft Compartment / Tailcone", "2A-8"),
        item("pf-empennage", "Empennage / controls / wicks / antennas / drains", "CHECKED", "Power Off Inspection — Empennage", "2A-9", { notices: [{ kind: "warning", text: "Vertical/horizontal stabilizers and flight-control surfaces must be free of frost, snow and ice." }] }),
        item("pf-left-nacelle", "Left nacelle / fire disks / oil / exhaust / reverser", "CHECKED", "Power Off Inspection — Left Nacelle", "2A-10"),
        item("pf-left-wing-aft", "Left wing aft / spoiler / flap / aileron / panels", "CHECKED", "Power Off Inspection — Left Wing Aft", "2A-11"),
        item("pf-left-tip", "Left tip tank / cap / drain / lights / jettison tube", "CHECKED", "Power Off Inspection — Left Tip Tank", "2A-11"),
        item("pf-left-wing-forward", "Left wing forward / vents / gear / inlet / cabin door seal", "CHECKED", "Power Off Inspection — Left Wing Forward", "2A-12–2A-13"),
      ],
    },
    {
      id: "preflight-power-cabin",
      title: "Preflight — power-on & cabin",
      sequence: 20,
      sources: [cae("Preflight Inspection — Power On Checks / Cabin Inspection", "2A-15")],
      items: [
        item("po-gear", "Landing gear switch", "DOWN", "Power On Checks", "2A-15"),
        item("po-batteries", "Battery switches", "BOTH ON", "Power On Checks", "2A-15"),
        item("po-fuel", "Fuel quantities", "CHECK", "Power On Checks", "2A-15"),
        item("po-pitot", "Pitot heat", "ON / TEST / OFF", "Power On Checks", "2A-15"),
        item("po-lights", "Exterior lights", "ON / TEST / OFF", "Power On Checks", "2A-15"),
        item("po-bat-off", "Battery switches", "BOTH OFF", "Power On Checks", "2A-15"),
        item("po-stall", "Stall warning system test", "PERFORM AS APPLICABLE", "Power On Checks", "2A-15", { condition: "CAE directs Standard Wing aircraft to the applicable AFM instructions." }),
        item("cabin-baggage", "Baggage", "SECURE", "Cabin Inspection", "2A-15"),
        item("cabin-air", "Cabin air damper / blower", "AS REQUIRED", "Cabin Inspection", "2A-15"),
        item("cabin-exit", "Emergency exit", "AISLE CLEAR / HANDLE UNOBSTRUCTED", "Cabin Inspection", "2A-15"),
        item("cabin-brief", "Passenger briefing", "COMPLETE", "Cabin Inspection", "2A-15"),
      ],
    },
    {
      id: "before-start",
      title: "Before Starting Engines",
      sequence: 30,
      sources: [cae("Expanded Normal Procedures — Before Starting Engines", "2B-5–2B-27")],
      items: [
        item("bs-initial-switches", "START-GEN / gear / fuel jettison / cabin-air initial positions", "VERIFIED", "Before Starting Engines", "2B-5"),
        item("bs-exit", "Emergency exit", "AISLE CLEAR / HANDLE UNOBSTRUCTED", "Before Starting Engines", "2B-5"),
        item("bs-oxygen", "Oxygen masks / valves / pressure", "100% / CHECKED", "Before Starting Engines", "2B-5", { verification: "CAE specifies checking oxygen pressure in the green band and crew-mask configuration." }),
        item("bs-cb", "Circuit breakers", "CHECKED", "Before Starting Engines", "2B-5"),
        item("bs-lock", "Control lock", "STOWED", "Before Starting Engines", "2B-6"),
        item("bs-seats", "Seat belts / harnesses / seats", "SECURED / ADJUSTED", "Before Starting Engines", "2B-6"),
        item("bs-controls", "Flight controls", "CHECKED", "Before Starting Engines", "2B-6"),
        item("bs-static-avionics", "Audio / static-source / avionics-master configuration", "CHECKED / SET", "Before Starting Engines", "2B-6", { condition: "Static-source configuration depends on installed FC-200 or FC-530 system." }),
        item("bs-fuel-comp", "Fuel computers", "ON", "Before Starting Engines", "2B-6"),
        item("bs-main-bat", "Main batteries", "CHECKED AND ON", "Before Starting Engines", "2B-6–2B-7"),
        item("bs-emerg-pwr", "Emergency power system", "CHECKED AND ON", "Before Starting Engines", "2B-6–2B-7"),
        item("bs-gpu", "GPU", "CONNECTED / CHECKED AS DESIRED", "Before Starting Engines", "2B-7"),
        item("bs-inverters", "Inverters / AC bus", "CHECKED / PRIMARY ON", "Before Starting Engines", "2B-7–2B-8", { condition: "Auxiliary inverter sequence applies only when installed." }),
        item("bs-antiskid", "Anti-skid", "ON", "Before Starting Engines", "2B-8"),
        item("bs-emerg-air", "Emergency air", "CHECKED", "Before Starting Engines", "2B-8", { verification: "CAE expanded procedure specifies 1,800 psi minimum." }),
        item("bs-hyd", "Hydraulic pressure", "CHECKED", "Before Starting Engines", "2B-8", { verification: "CAE expanded procedure specifies 1,000 psi minimum; use auxiliary pump if required, then return it OFF." }),
        item("bs-pb", "Parking brake", "SET", "Before Starting Engines", "2B-8"),
        item("bs-em-brake", "Emergency brake", "CHECKED", "Before Starting Engines", "2B-8"),
        item("bs-warning-light", "Warning light test", "PERFORMED", "Before Starting Engines", "2B-9"),
        item("bs-gear-warning", "Landing gear switch / warning", "DOWN / TESTED", "Before Starting Engines", "2B-9"),
        item("bs-fire", "Fire detection system", "CHECKED", "Before Starting Engines", "2B-9"),
        item("bs-fuel", "Fuel balance / quantities / counter", "CHECKED / ZERO", "Before Starting Engines", "2B-9"),
        item("bs-jet", "Jet pumps", "ON", "Before Starting Engines", "2B-9"),
        item("bs-crossflow", "Standby pumps / crossflow", "CHECKED", "Before Starting Engines", "2B-9–2B-10"),
        item("bs-fuel-panel", "Crossflow / XFER-FILL / FUS VAL", "CLOSED / OFF / OFF", "Before Starting Engines", "2B-10"),
        item("bs-warning-systems", "Warning systems", "CHECKED", "Before Starting Engines", "2B-10–2B-14", { explanation: "Expanded checks include cabin-altitude, Mach warning/stick puller, Mach trim and stall-warning logic as applicable to the installed AFCS/wing configuration." }),
        item("bs-press", "Pressurization", "AUTO / ALTITUDE / RATE SET", "Before Starting Engines", "2B-15"),
        item("bs-temp-bleed", "Temperature controls / bleed air", "AS DESIRED / ON", "Before Starting Engines", "2B-15"),
        item("bs-told", "TOLD data / bugs", "COMPUTED / SET", "Before Starting Engines", "2B-15"),
        item("bs-ice-detect", "Ice detect lights", "CHECKED", "Before Starting Engines", "2B-15"),
        item("bs-em-gyro", "Emergency gyro", "UNCAGED", "Before Starting Engines", "2B-15"),
        item("bs-cvr", "CVR", "TEST", "Before Starting Engines", "2B-15"),
        item("bs-trim", "Trim / pitch-roll-yaw / selectors", "CHECKED / SET / PRIMARY", "Before Starting Engines", "2B-15–2B-21", { condition: "Detailed trim test sequence depends on installed FC-200/FC-530 and applicable modification status." }),
        item("bs-ap", "Autopilot monitor", "CHECKED", "Before Starting Engines", "2B-22–2B-24", { condition: "Use the installed FC-200 or FC-530 test sequence." }),
        item("bs-yd", "Yaw dampers", "CHECKED", "Before Starting Engines", "2B-24–2B-27", { condition: "Use the installed FC-200 or FC-530 test sequence." }),
        item("bs-em-lights", "Emergency lights", "TESTED / ARMED", "Before Starting Engines", "2B-27", { condition: "If installed." }),
      ],
    },
    {
      id: "starting-engines",
      title: "Starting Engines",
      sequence: 40,
      sources: [cae("Expanded Normal Procedures — Starting Engines", "2B-28–2B-32")],
      items: [
        item("se-pax", "Passengers / baggage", "BRIEFED / SECURED", "Starting Engines", "2B-28"),
        item("se-door", "Cabin door", "TWO HANDLES FORWARD / LIGHT OUT", "Starting Engines", "2B-28"),
        item("se-fuel-comp", "L/R fuel computers / lights", "ON / OUT", "Starting Engines", "2B-28"),
        item("se-bat", "Batteries", "MINIMUM VOLTAGE CHECKED", "Starting Engines", "2B-28"),
        item("se-inverter", "Inverters", "PRI ON", "Starting Engines", "2B-28"),
        item("se-climate", "Air conditioning / auxiliary heat", "FAN OR OFF", "Starting Engines", "2B-28"),
        item("se-beacon", "Rotating beacon / external lighting", "ON / AS REQUIRED", "Starting Engines", "2B-28"),
        item("se-thrust", "Thrust levers", "CUTOFF", "Starting Engines", "2B-28"),
        item("se-pb", "Parking brake / hydraulic pump", "SET / OFF", "Starting Engines", "2B-28"),
        item("se-engines", "Engines", "START", "Starting Engines", "2B-29–2B-31", { explanation: "Expanded sequence: START selected; minimum 10% N2 with fan rotation before IDLE; monitor fuel flow, ITT, N1 and oil pressure; verify START and AIR IGN extinguish at approximately 45–50% N2.", notices: [{ kind: "caution", text: "Observe the CAE starter cooling schedule after an unsuccessful start attempt." }] }),
        item("se-instruments", "Engine instruments / starter disengagement", "CHECKED", "Starting Engines", "2B-31"),
        item("se-gpu", "GPU", "DISCONNECTED", "Starting Engines", "2B-31"),
        item("se-generators", "Generators / DC volts and amps", "ON / CHECKED", "Starting Engines", "2B-32"),
        item("se-current-limiters", "Current limiters", "CHECKED", "Starting Engines", "2B-32"),
      ],
    },
    {
      id: "before-taxi",
      title: "Before Taxi",
      sequence: 50,
      sources: [cae("Expanded Normal Procedures — Before Taxi", "2B-33–2B-36")],
      items: [
        item("bt-inverters", "Inverters", "ALL ON", "Before Taxi", "2B-33"),
        item("bt-avionics", "Avionics / avionics master", "ON", "Before Taxi", "2B-33"),
        item("bt-radar", "Radar", "STANDBY", "Before Taxi", "2B-33"),
        item("bt-ra-ap", "Radio altimeter / autopilot / emergency power", "ON", "Before Taxi", "2B-33"),
        item("bt-nav", "Navigation system / GPWS / TCAS", "PROGRAMMED / TESTED", "Before Taxi", "2B-33", { condition: "Installed navigation/alerting equipment varies by aircraft configuration." }),
        item("bt-wshld", "Windshield heat", "PURGED / CHECKED", "Before Taxi", "2B-34", { condition: "Procedure differs for 450 and 510 pressurization installations." }),
        item("bt-governor", "Fuel-control governors", "CHECKED", "Before Taxi", "2B-34–2B-35"),
        item("bt-antiskid", "Anti-skid", "ON / LIGHTS OUT", "Before Taxi", "2B-35"),
        item("bt-spoilers", "Spoileron / spoilers", "CHECKED / RETRACTED", "Before Taxi", "2B-35–2B-36"),
        item("bt-flaps", "Flaps", "8° OR 20° SET", "Before Taxi", "2B-36"),
        item("bt-hyd", "Hydraulic pressure / low hydraulic light", "CHECKED", "Before Taxi", "2B-36"),
        item("bt-lighting", "Lighting", "ON / AS REQUIRED", "Before Taxi", "2B-36"),
        item("bt-cb", "Circuit breakers", "CHECKED IN", "Before Taxi", "2B-36"),
        item("bt-pb", "Parking brake", "RELEASED", "Before Taxi", "2B-36"),
      ],
    },
    {
      id: "taxi",
      title: "Taxi",
      sequence: 60,
      sources: [cae("Expanded Normal Procedures — Taxi", "2B-37–2B-40")],
      items: [
        item("taxi-brakes-steering", "Brakes and steering", "CHECKED / ENGAGED", "Taxi", "2B-37"),
        item("taxi-reversers", "Thrust reversers", "CHECKED", "Taxi", "2B-37–2B-39", { condition: "Use the procedure for the installed Aeronca or Dee Howard system." }),
        item("taxi-controls", "Flight controls", "CHECKED", "Taxi", "2B-39"),
        item("taxi-instruments", "Flight instruments", "NO FLAGS / ALTITUDE & HEADING VERIFIED", "Taxi", "2B-39"),
        item("taxi-nav", "Navigation equipment / radios", "ON / SET", "Taxi", "2B-39"),
        item("taxi-config", "Spoilers / flaps / trim", "RETRACTED / 8° OR 20° / SET-CHECKED", "Taxi", "2B-39"),
        item("taxi-press", "Pressurization / cabin air", "CHECKED / NORM OR ON", "Taxi", "2B-39–2B-40"),
        item("taxi-antiice", "Anti-ice systems", "CHECKED / AS REQUIRED", "Taxi", "2B-40", { notices: [{ kind: "warning", text: "Aircraft surfaces and engine inlets must be free of frost, snow and ice before flight." }] }),
        item("taxi-cabin", "Cabin check", "COMPLETED", "Taxi", "2B-40"),
      ],
    },
    {
      id: "before-takeoff",
      title: "Before Takeoff",
      sequence: 70,
      sources: [cae("Expanded Normal Procedures — Before Takeoff", "2B-41")],
      items: [
        item("bto-brief", "Crew briefing / takeoff data and bugs", "COMPLETED / REVIEWED", "Before Takeoff", "2B-41"),
        item("bto-fuel", "Fuel balance", "CHECKED", "Before Takeoff", "2B-41"),
        item("bto-cabin", "Cabin air", "NORM OR ON", "Before Takeoff", "2B-41"),
        item("bto-antiice", "Anti-ice", "AS REQUIRED", "Before Takeoff", "2B-41"),
        item("bto-radar", "Radar", "AS DESIRED", "Before Takeoff", "2B-41"),
        item("bto-xpdr", "Transponder", "TA/RA", "Before Takeoff", "2B-41"),
        item("bto-tr", "Dee Howard thrust reversers", "ARMED", "Before Takeoff", "2B-41", { condition: "If installed." }),
      ],
    },
    {
      id: "runway-lineup",
      title: "Runway Line-Up",
      sequence: 80,
      sources: [cae("Expanded Normal Procedures — Runway Line-Up", "2B-42")],
      items: [
        item("rl-pitot", "Pitot heat", "CHECKED / ON", "Runway Line-Up", "2B-42"),
        item("rl-ign", "Air ignition", "ON", "Runway Line-Up", "2B-42"),
        item("rl-stall", "Stall warnings", "ON", "Runway Line-Up", "2B-42"),
        item("rl-pb", "Parking brake", "RELEASED", "Runway Line-Up", "2B-42"),
        item("rl-lights", "Landing/taxi and recognition/strobe lights", "ON / AS DESIRED", "Runway Line-Up", "2B-42"),
        item("rl-steer", "Steer lock", "OFF", "Runway Line-Up", "2B-42"),
        item("rl-warning", "Warning lights", "EXTINGUISHED / AS APPROPRIATE", "Runway Line-Up", "2B-42"),
      ],
    },
    {
      id: "takeoff",
      title: "Takeoff",
      sequence: 90,
      sources: [cae("Expanded Normal Procedures — Takeoff", "2B-42")],
      items: [
        item("to-nws", "Nosewheel steering", "RELEASE AT FIRST AIRSPEED INDICATION", "Takeoff", "2B-42"),
      ],
    },
    {
      id: "after-takeoff",
      title: "After Takeoff",
      sequence: 100,
      sources: [cae("Expanded Normal Procedures — After Takeoff", "2B-43–2B-44")],
      items: [
        item("ato-gear", "Landing gear", "UP", "After Takeoff", "2B-43"),
        item("ato-yd", "Yaw damper PRI or SEC", "ENGAGED", "After Takeoff", "2B-43"),
        item("ato-flaps", "Flaps", "UP", "After Takeoff", "2B-43", { explanation: "CAE notes flaps may be retracted at V2 + 30 and must be retracted before VFE." }),
        item("ato-tr", "Dee Howard thrust reversers", "OFF PRIOR TO 200 KIAS", "After Takeoff", "2B-43", { condition: "If installed." }),
        item("ato-antiice", "Anti-ice systems", "AS REQUIRED", "After Takeoff", "2B-43"),
        item("ato-ign", "Air ignition", "AS REQUIRED OR OFF", "After Takeoff", "2B-44"),
        item("ato-lights", "Landing/taxi lights", "OFF", "After Takeoff", "2B-44"),
        item("ato-press", "Pressurization", "MONITORED", "After Takeoff", "2B-44"),
        item("ato-appr", "Autopilot APPR light", "OUT", "After Takeoff", "2B-44"),
        item("ato-hyd", "Hydraulic pressure", "NORMAL", "After Takeoff", "2B-44"),
        item("ato-aoa", "Angle-of-attack indicators", "CROSS-CHECKED", "After Takeoff", "2B-44", { notices: [{ kind: "caution", text: "Ice accumulation can make AOA indications unreliable and may cause aerodynamic stall before shaker/pusher activation." }] }),
      ],
    },
    {
      id: "climb",
      title: "Climb",
      sequence: 110,
      sources: [cae("Expanded Normal Procedures — Climb", "2B-45")],
      items: [
        item("climb-10k", "At 10,000 ft — signs", "AS REQUIRED", "Climb", "2B-45"),
        item("climb-alt", "At FL180 / transition level — altimeters", "29.92 / STANDARD", "Climb", "2B-45"),
        item("climb-climate", "Cool/Fan / emergency pressurization / recognition light", "SET AS APPLICABLE", "Climb", "2B-45"),
        item("climb-o2", "Leaving FL250 — crew masks", "100% OXY / QUICK-DON POSITION", "Climb", "2B-45", { condition: "Exact requirement varies with serial number/mask installation." }),
        item("climb-high-o2", "Above FL410 — oxygen masks", "AS REQUIRED BY CONFIGURATION", "Climb", "2B-45", { condition: "Serial-number dependent." }),
      ],
    },
    {
      id: "cruise",
      title: "Cruise",
      sequence: 120,
      sources: [cae("Expanded Normal Procedures — Cruise", "2B-46")],
      items: [
        item("cruise-press", "Pressurization", "MONITORED", "Cruise", "2B-46"),
        item("cruise-engine", "Engine instruments", "MONITORED", "Cruise", "2B-46"),
        item("cruise-ap", "Autopilot", "AS DESIRED", "Cruise", "2B-46"),
        item("cruise-wshld", "Windshield heat", "AS DESIRED", "Cruise", "2B-46"),
        item("cruise-fuel", "Fuel management", "MONITORED", "Cruise", "2B-46"),
      ],
    },
    {
      id: "descent",
      title: "Descent",
      sequence: 130,
      sources: [cae("Expanded Normal Procedures — Descent", "2B-46")],
      items: [
        item("des-wshld", "Windshield heat / defog", "AS REQUIRED", "Descent", "2B-46"),
        item("des-press", "Pressurization", "SET FOR LANDING", "Descent", "2B-46"),
        item("des-antiice", "Anti-ice systems", "AS REQUIRED", "Descent", "2B-46"),
        item("des-alt", "Transition level — altimeters", "SET / CROSS-CHECKED", "Descent", "2B-46"),
        item("des-ac", "Air conditioner", "AS DESIRED", "Descent", "2B-46"),
        item("des-hyd", "Hydraulic pressure", "CHECKED", "Descent", "2B-46"),
        item("des-recog", "Recognition light", "ON", "Descent", "2B-46"),
        item("des-told", "TOLD card / bugs", "COMPUTED / SET", "Descent", "2B-46"),
        item("des-cabin", "Cabin / seats / tables / exit / signs", "CHECKED / SECURED", "Descent", "2B-46"),
      ],
    },
    {
      id: "approach",
      title: "Approach",
      sequence: 140,
      sources: [cae("Expanded Normal Procedures — Approach", "2B-47")],
      items: [
        item("app-cb", "Circuit breakers", "CHECKED", "Approach", "2B-47"),
        item("app-tr", "Aeronca thrust reversers", "TESTED", "Approach", "2B-47", { condition: "If installed." }),
        item("app-pressure", "Hydraulic / emergency air pressure", "CHECKED", "Approach", "2B-47"),
        item("app-mins", "Radio / barometric altimeters", "MINS SET / CROSS-CHECKED", "Approach", "2B-47"),
        item("app-fuel", "Fuel balance", "CHECKED", "Approach", "2B-47"),
        item("app-avionics", "Avionics", "SET FOR APPROACH", "Approach", "2B-47"),
        item("app-brief", "Crew briefing / bugs", "COMPLETED / SET", "Approach", "2B-47", { explanation: "CAE recommends adding one-half the gust factor to approach speed for gusty wind conditions." }),
      ],
    },
    {
      id: "before-landing",
      title: "Before Landing",
      sequence: 150,
      sources: [cae("Expanded Normal Procedures — Before Landing", "2B-48")],
      items: [
        item("bl-spoilers", "Spoilers", "RETRACTED", "Before Landing", "2B-48"),
        item("bl-flaps20", "Flaps", "AS DESIRED — 8° OR 20°", "Before Landing", "2B-48"),
        item("bl-gear", "Landing gear", "DOWN", "Before Landing", "2B-48"),
        item("bl-sync", "Engine sync", "OFF", "Before Landing", "2B-48"),
        item("bl-antiskid", "Anti-skid", "ON / LIGHTS OUT", "Before Landing", "2B-48"),
        item("bl-lights", "Landing/taxi lights", "ON", "Before Landing", "2B-48"),
        item("bl-tr", "Dee Howard thrust reversers", "ARMED BELOW 200 KIAS", "Before Landing", "2B-48", { condition: "If installed." }),
        item("bl-cabin", "Cabin", "CHECKED", "Before Landing", "2B-48"),
        item("bl-flaps", "Flaps", "DOWN", "Before Landing", "2B-48"),
        item("bl-hyd", "Hydraulic pressure", "CHECKED", "Before Landing", "2B-48"),
        item("bl-ign", "Air ignition", "ON", "Before Landing", "2B-48"),
        item("bl-ap", "Autopilot", "DISENGAGED", "Before Landing", "2B-48"),
        item("bl-yd", "Yaw damper", "DISENGAGED AS APPLICABLE", "Before Landing", "2B-48", { condition: "Landing logic differs for FC-200 and FC-530 installations and flap configuration." }),
      ],
    },
    {
      id: "landing",
      title: "Landing",
      sequence: 160,
      sources: [cae("Expanded Normal Procedures — Landing", "2B-49")],
      items: [
        item("land-spoilers", "After touchdown — spoilers", "EXTENDED", "Landing", "2B-49"),
        item("land-brakes", "Brakes", "AS REQUIRED", "Landing", "2B-49"),
        item("land-reverse", "Thrust reversers / drag chute", "AS DESIRED", "Landing", "2B-49", { condition: "Installed equipment only." }),
        item("land-nws", "Below 45 kt — nosewheel steering", "AS REQUIRED", "Landing", "2B-49"),
      ],
    },
    {
      id: "go-around",
      title: "Go-Around / Missed Approach",
      sequence: 170,
      sources: [cae("Expanded Normal Procedures — Go-Around / Missed Approach", "2B-49")],
      items: [
        item("ga-ap", "Autopilot", "DISENGAGED", "Go-Around / Missed Approach", "2B-49"),
        item("ga-power", "Thrust levers", "T.O. POWER OR AS REQUIRED", "Go-Around / Missed Approach", "2B-49"),
        item("ga-spoiler", "Spoiler switch", "RETRACTED", "Go-Around / Missed Approach", "2B-49"),
        item("ga-flaps20", "Flaps", "20°", "Go-Around / Missed Approach", "2B-49"),
        item("ga-gear", "Landing gear", "UP", "Go-Around / Missed Approach", "2B-49"),
        item("ga-speed", "Climb", "APPROACH CLIMB SPEED", "Go-Around / Missed Approach", "2B-49"),
        item("ga-clean", "Clear of obstacles — airspeed / flaps", "VREF + 30 / UP", "Go-Around / Missed Approach", "2B-49", { notices: [{ kind: "warning", text: "CAE warns that low wing-tank fuel combined with prolonged 10°+ nose-up attitude can trap fuel and lead to starvation/flameout." }] }),
      ],
    },
    {
      id: "after-landing",
      title: "After Landing / Clearing Runway",
      sequence: 180,
      sources: [cae("Expanded Normal Procedures — After Landing / Clearing Runway", "2B-50")],
      items: [
        item("al-antiice", "Anti-ice system", "AS REQUIRED", "After Landing / Clearing Runway", "2B-50"),
        item("al-ign", "Air ignition / stall warnings", "OFF / OFF", "After Landing / Clearing Runway", "2B-50"),
        item("al-lights", "Landing/taxi lights", "AS DESIRED", "After Landing / Clearing Runway", "2B-50"),
        item("al-cabin", "Cabin air", "OFF", "After Landing / Clearing Runway", "2B-50"),
        item("al-recog", "Recognition / strobe lights", "OFF", "After Landing / Clearing Runway", "2B-50"),
        item("al-avionics", "Unnecessary avionics / radar / UNS", "OFF", "After Landing / Clearing Runway", "2B-50"),
        item("al-xpdr", "Transponder", "STANDBY OR OFF", "After Landing / Clearing Runway", "2B-50"),
        item("al-spoilers", "Spoilers", "RETRACTED", "After Landing / Clearing Runway", "2B-50"),
        item("al-flaps", "Flaps", "AS REQUIRED", "After Landing / Clearing Runway", "2B-50"),
        item("al-hyd", "Hydraulic pressure", "CHECKED", "After Landing / Clearing Runway", "2B-50"),
        item("al-trim", "Trims", "RESET", "After Landing / Clearing Runway", "2B-50"),
        item("al-tr", "Dee Howard thrust reversers", "OFF", "After Landing / Clearing Runway", "2B-50", { condition: "If installed." }),
      ],
    },
    {
      id: "shutdown",
      title: "Shutdown",
      sequence: 190,
      sources: [cae("Expanded Normal Procedures — Shutdown", "2B-51–2B-52")],
      items: [
        item("sd-chocks", "Chocks / parking brake", "AS REQUIRED", "Shutdown", "2B-51"),
        item("sd-antiice", "Anti-ice systems", "OFF", "Shutdown", "2B-51"),
        item("sd-em", "Emergency power / standby gyro", "OFF / CAGED", "Shutdown", "2B-51"),
        item("sd-panel", "Panel switches / avionics", "OFF", "Shutdown", "2B-51"),
        item("sd-crossflow", "Crossflow", "CLOSED", "Shutdown", "2B-51", { notices: [{ kind: "caution", text: "CAE warns that leaving crossflow open can allow gravity transfer to the low wing and potentially tip the aircraft on the ramp." }] }),
        item("sd-transfer", "Fuel tank XFER-FILL / fuel valve", "OFF / CLOSED", "Shutdown", "2B-51"),
        item("sd-emlights", "Emergency lights", "DISARMED", "Shutdown", "2B-51", { condition: "If installed." }),
        item("sd-coffee", "Coffee / oven", "OFF", "Shutdown", "2B-51"),
        item("sd-thrust", "Thrust levers", "CUTOFF", "Shutdown", "2B-51"),
        item("sd-ext", "External lighting / inverters / generators", "OFF", "Shutdown", "2B-51"),
        item("sd-hyd", "Hydraulic pressure", "ZERO AS APPLICABLE", "Shutdown", "2B-52"),
        item("sd-batteries", "Batteries", "OFF", "Shutdown", "2B-52"),
        item("sd-lock", "Control lock", "INSTALLED", "Shutdown", "2B-52"),
      ],
    },
    {
      id: "quick-turnaround",
      title: "Quick Turnaround",
      sequence: 200,
      sources: [cae("Expanded Normal Procedures — Quick Turnaround", "2B-53–2B-55")],
      items: [
        item("qt-door", "Cabin door", "CLOSED / LOCKED / LIGHT OUT", "Quick Turnaround", "2B-53"),
        item("qt-signs", "No smoking / seat belt", "ON", "Quick Turnaround", "2B-53"),
        item("qt-climate", "Cool fan / auxiliary heat", "OFF OR FAN", "Quick Turnaround", "2B-53"),
        item("qt-engine", "Engine if shut down", "START / GEN", "Quick Turnaround", "2B-53"),
        item("qt-elec", "DC volts/amps / starter disengagement / current limiters", "CHECKED", "Quick Turnaround", "2B-53"),
        item("qt-cb", "Circuit breakers", "IN", "Quick Turnaround", "2B-53"),
        item("qt-avionics", "Avionics / anti-ice / cabin equipment", "AS REQUIRED", "Quick Turnaround", "2B-53"),
        item("qt-taxi", "Fuel / TOLD / nav / transponder / radar / configuration / pressurization", "CHECKED / SET", "Quick Turnaround — Taxi", "2B-53–2B-54"),
        item("qt-brief", "Cabin and takeoff briefings", "COMPLETED", "Quick Turnaround — Taxi", "2B-54"),
      ],
    },
  ],
};
