import type {
  AircraftApplicability,
  AircraftChecklistContent,
  AircraftChecklistItem,
  TrainingSourceReference,
} from "../../../lib/universal-aircraft-content.ts";

function source(
  pageLabel: string,
  section: string,
): readonly TrainingSourceReference[] {
  return [{
    manualId: "CL-102B",
    chapter: "Normal Procedures",
    section,
    pageLabel,
    note: "Bombardier Learjet Model 35/36 Crew Checklist & Quick Reference Handbook CL-102B.",
  }];
}

function item(
  id: string,
  challenge: string,
  response: string | undefined,
  pageLabel: string,
  section: string,
  applicability?: AircraftApplicability,
): AircraftChecklistItem {
  return {
    id,
    challenge,
    ...(response ? { response } : {}),
    ...(applicability ? { applicability } : {}),
    sources: source(pageLabel, section),
  };
}

const rosemount: AircraftApplicability = {
  equipmentAllOf: ["rosemount-pitot-static"],
};

const nonRosemount: AircraftApplicability = {
  equipmentNoneOf: ["rosemount-pitot-static"],
};

const fc530: AircraftApplicability = {
  equipmentAllOf: ["fc-530"],
};




const thrustReverserInstalled: AircraftApplicability = {
  configurationEquipmentAllOf: ["thrust-reverser"],
};

const dragChuteInstalled: AircraftApplicability = {
  configurationEquipmentAllOf: ["drag-chute"],
};







export const learjet35aNormalChecklist: AircraftChecklistContent = {
  aircraftId: "learjet-35a",
  title: "Learjet 35A/36A Normal Checklist",
  sourcePolicy: "available-sources",
  sourceNote:
    "Normal checklist content transcribed from Bombardier CL-102B. Page-level effectivity and configuration distinctions are retained where the current applicability contract can represent them.",
  disclaimer:
    "Operating reference only. The current approved AFM and aircraft/operator documents remain controlling.",
  phases: [
    {
      id: "exterior-preflight",
      title: "Exterior Preflight",
      sequence: 10,
      sources: source("N-2–N-4", "Exterior Preflight"),
      items: [
        item("exterior-controls-lock", "Controls Lock", "REMOVE & STOW", "N-2", "Exterior Preflight"),
        item("exterior-pilot-defog-nozzle", "Pilot’s Defog Nozzle", "CLEAR", "N-2", "Exterior Preflight"),
        item("exterior-left-stall-pitot-static", "Left Stall Vane, Pitot-Static & Static Ports", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-left-pitot-drains", "Left Pitot-Static Drains", "DRAIN AS REQ’D", "N-2", "Exterior Preflight"),
        item("exterior-nose-strut", "Nose Strut & Wheel Well", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-nose-wheel", "Nose Wheel & Tire", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-radome", "Radome", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-oxygen-valve-disc", "Oxygen Valve & Discharge Disc", "CHECK, IF APPLICABLE", "N-2", "Exterior Preflight"),
        item("exterior-total-temp", "Total Temp Probe & Press Static Port", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-right-stall-pitot-static", "Right Stall Vane, Pitot-Static & Static Ports", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-right-pitot-drains", "Right Pitot-Static Drains", "DRAIN AS REQ’D", "N-2", "Exterior Preflight"),
        item("exterior-copilot-defog-nozzle", "Copilot’s Defog Nozzle", "CLEAR", "N-2", "Exterior Preflight"),
        item("exterior-lower-fuselage", "Lower Fuselage", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-emergency-exit", "Emergency Exit", "SECURE", "N-2", "Exterior Preflight"),
        item("exterior-upper-fuselage", "Upper Fuselage", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-right-engine-inlet", "Right Engine Inlet", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-fuselage-fuel-drains-forward", "Fuselage Fuel Drains", "DRAIN", "N-2", "Exterior Preflight"),
        item("exterior-right-main-strut", "Right Main Strut & Wheel Well", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-right-main-wheels", "Right Main Wheels, Tires & Brakes", "CHECK", "N-2", "Exterior Preflight"),
        item("exterior-right-wing", "Right Wing", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-right-stall-strip", "Right Stall Strip & Stall Fence (if installed)", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-right-tip-tank", "Right Tip Tank", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-right-tip-sump", "Right Tip Tank Sump", "DRAIN", "N-3", "Exterior Preflight"),
        item("exterior-right-fuel-cap", "Right Fuel Cap", "SECURE", "N-3", "Exterior Preflight"),
        item("exterior-right-nav-static", "Right Nav Light & Static Wicks (2)", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-right-aileron-spoiler-flap", "Right Aileron, Spoiler & Flap", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-right-ble-vg", "Right Boundary Layer Energizers or Vortex Generators", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-right-engine", "Right Engine", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-fuel-vent", "Fuel Vent", "DRAIN COMPLETELY", "N-3", "Exterior Preflight"),
        item("exterior-fuselage-fuel-drains-aft", "Fuselage Fuel Drains", "DRAIN", "N-3", "Exterior Preflight"),
        item("exterior-tailcone", "Tailcone Interior", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-drag-chute", "Drag Chute", "CHECK", "N-3", "Exterior Preflight", dragChuteInstalled),
        item("exterior-right-fuselage", "Right Fuselage", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-right-fuel-computer-drain", "Right Fuel Computer Drain", "DRAIN", "N-3", "Exterior Preflight"),
        item("exterior-oxygen-disc", "Oxygen Discharge Disc", "CHECK, IF APPLICABLE", "N-3", "Exterior Preflight"),
        item("exterior-tail-static", "Tail Section & Static Wicks (8)", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-tailstand", "Tailstand", "REMOVE", "N-3", "Exterior Preflight"),
        item("exterior-left-fuselage", "Left Fuselage", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-left-fuel-computer-drain", "Left Fuel Computer Drain", "DRAIN", "N-3", "Exterior Preflight"),
        item("exterior-fire-discs", "Fire Extinguisher Discs", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-left-engine", "Left Engine", "CHECK", "N-3", "Exterior Preflight"),
        item("exterior-left-spoiler-flap-aileron", "Left Spoiler, Flap & Aileron", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-ble-vg", "Left Boundary Layer Energizers or Vortex Generators", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-nav-static", "Left Nav Light & Static Wicks (2)", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-fuel-cap", "Left Fuel Cap", "SECURE", "N-4", "Exterior Preflight"),
        item("exterior-left-wing", "Left Wing", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-tip-tank", "Left Tip Tank", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-tip-sump", "Left Tip Tank Sump", "DRAIN", "N-4", "Exterior Preflight"),
        item("exterior-left-stall-strip", "Left Stall Strip & Stall Fence (if installed)", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-main-strut", "Left Main Strut & Wheel Well", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-main-wheels", "Left Main Wheels, Tires & Brakes", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-left-engine-inlet", "Left Engine Inlet", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-gear-switch", "Landing Gear Switch", "DN", "N-4", "Exterior Preflight"),
        item("exterior-battery-on", "Battery Switches", "ON", "N-4", "Exterior Preflight"),
        item("exterior-fuel-quantities", "Fuel Quantities", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-heat-check", "Pitot-Static/Stall Vane/Temp Probe Heat", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-lights", "Exterior Lights", "CHECK", "N-4", "Exterior Preflight"),
        item("exterior-battery-off", "Battery Switches", "OFF", "N-4", "Exterior Preflight"),
      ],
    },
    {
      id: "cabin-preflight",
      title: "Cabin Preflight",
      sequence: 20,
      sources: source("N-4", "Cabin Preflight"),
      items: [
        item("cabin-baggage", "Baggage", "SECURED", "N-4", "Cabin Preflight"),
        item("cabin-air-damper", "Cabin Air Damper", "AS REQ’D", "N-4", "Cabin Preflight"),
        item("cabin-emergency-exit", "Emergency Exit", "SECURED & CLEAR", "N-4", "Cabin Preflight"),
        item("cabin-passengers", "Passengers", "BRIEFED", "N-4", "Cabin Preflight"),
      ],
    },
    {
      id: "before-starting-engines",
      title: "Before Starting Engines",
      sequence: 30,
      sources: source("N-5–N-7", "Before Starting Engines"),
      items: [
        item("bse-controls-lock", "Controls Lock", "STOWED", "N-5", "Before Starting Engines"),
        item("bse-belts-seats", "Safety Belts, Shoulder Harnesses & Seats", "SECURE & ADJUST", "N-5", "Before Starting Engines"),
        item("bse-flight-controls", "Flight Controls", "CHECK", "N-5", "Before Starting Engines"),
        item("bse-pass-mask-valve", "Passenger Mask Valve", "AUTO", "N-5", "Before Starting Engines"),
        item("bse-pass-oxygen-valve", "Passenger Oxygen Valve", "NORM", "N-5", "Before Starting Engines"),
        item("bse-oxygen-pressure", "Oxygen Pressure", "CHECK", "N-5", "Before Starting Engines"),
        item("bse-crew-masks", "Crew Masks", "CHECK & SELECT 100%", "N-5", "Before Starting Engines"),
        item("bse-circuit-breakers", "Circuit Breakers", "IN", "N-5", "Before Starting Engines"),
        item("bse-gear-switch", "Landing Gear Switch", "DN", "N-5", "Before Starting Engines"),
        item("bse-emergency-battery", "Emergency Battery(ies)", "CHECK & ON", "N-5", "Before Starting Engines"),
        item("bse-panel-avionics", "Panel Switches & Avionics", "OFF or SET", "N-5", "Before Starting Engines"),
        item("bse-alt-static", "ALT Static", "CLOSED", "N-5", "Before Starting Engines", nonRosemount),
        item("bse-pilot-altimeter", "Pilot’s Altimeter", "NORM", "N-5", "Before Starting Engines", nonRosemount),
        item("bse-static-source", "Static Source", "BOTH", "N-5.1", "Before Starting Engines", rosemount),
        item("bse-batteries", "Batteries", "CHECK & ON", "N-5", "Before Starting Engines"),
        item("bse-gpu", "GPU (if desired)", "CONNECT & ON", "N-5", "Before Starting Engines"),
        item("bse-inverters", "Inverters", "CHECK & ON", "N-5", "Before Starting Engines"),
        item("bse-emergency-lights", "Emergency Lights (if installed)", "TEST & ARMED", "N-5", "Before Starting Engines"),
        item("bse-hyd-pressure", "Hydraulic Pressure", "CHECK", "N-6", "Before Starting Engines"),
        item("bse-emergency-air", "Emergency Air Pressure", "CHECK", "N-6", "Before Starting Engines"),
        item("bse-parking-brake", "Parking Brake", "SET", "N-6", "Before Starting Engines"),
        item("bse-emergency-brake", "Emergency Brake Handle", "PULL FROM RECESS, THEN RETURN", "N-6", "Before Starting Engines"),
        item("bse-hyd-pump", "Hyd Pump", "OFF", "N-6", "Before Starting Engines"),
        item("bse-annunciator", "Annunciator Lights", "TEST", "N-6", "Before Starting Engines"),
        item("bse-ice-detect", "Ice Detect Lights", "CHECK", "N-6", "Before Starting Engines"),
        item("bse-gear-warning", "Gear Warning", "TEST", "N-6", "Before Starting Engines"),
        item("bse-fire-detect", "Fire Detect", "TEST", "N-6", "Before Starting Engines"),
        item("bse-cabin-altitude", "Cabin Altitude", "TEST", "N-6", "Before Starting Engines"),
        item("bse-stick-puller-mach", "Stick Puller/Mach Warning", "CHECK", "N-6", "Before Starting Engines"),
        item("bse-mach-trim", "Mach Trim", "TEST", "N-6", "Before Starting Engines"),
        item("bse-stall-warning", "Stall Warning System (L & R)", "TEST", "N-6", "Before Starting Engines"),
        item("bse-standby-gyro", "Standby Gyro", "UNCAGE, GYRO ERECT", "N-6", "Before Starting Engines"),
        item("bse-bleed-air", "L and R Bleed Air Switches", "ON", "N-6", "Before Starting Engines"),
        item("bse-cabin-air", "Cabin Air", "OFF", "N-6", "Before Starting Engines"),
        item("bse-auto-man", "Auto-Man Switch", "AS DESIRED", "N-6", "Before Starting Engines"),
        item("bse-cabin-controller", "Cabin Controller", "CRUISE ALTITUDE", "N-6", "Before Starting Engines"),
        item("bse-rate-selector", "Rate Selector", "AS DESIRED", "N-6", "Before Starting Engines"),
        item("bse-in-normal-out-defog", "IN NORMAL/OUT DEFOG Knob (if installed)", "PUSH IN", "N-6", "Before Starting Engines"),
        item("bse-cabin-temp", "Cabin Temp Controls", "AS DESIRED", "N-6", "Before Starting Engines"),
        item("bse-secondary-pitch", "Secondary Pitch & Cutout", "CHECK", "N-7", "Before Starting Engines"),
        item("bse-primary-pitch", "Primary Pitch & Cutout", "CHECK", "N-7", "Before Starting Engines"),
        item("bse-trim-speed-fc530", "Trim Speed", "CHECK", "N-7", "Before Starting Engines", fc530),
        item("bse-trim-monitor-fc530", "Trim Monitor", "CHECK", "N-7", "Before Starting Engines", fc530),
        item("bse-aileron-trim", "Aileron", "CHECK", "N-7", "Before Starting Engines"),
        item("bse-rudder-trim", "Rudder", "CHECK", "N-7", "Before Starting Engines"),
        item("bse-takeoff-trim", "Takeoff Trim (all three axes)", "SET", "N-7", "Before Starting Engines"),
        item("bse-autopilot-monitor", "Autopilot Monitor", "CHECK", "N-7", "Before Starting Engines"),
        item("bse-yaw-dampers", "Yaw Dampers", "CHECK", "N-7", "Before Starting Engines"),
        item("bse-fuel-counter", "Fuel Counter", "ZERO", "N-7", "Before Starting Engines"),
        item("bse-fuel-quantities", "Fuel Quantities", "CHECK", "N-7", "Before Starting Engines"),
        item("bse-crossflow", "Crossflow Valve", "CLOSE", "N-7", "Before Starting Engines"),
        item("bse-transfer-fill", "Transfer — Fill", "OFF", "N-7", "Before Starting Engines"),
        item("bse-standby-pumps", "Standby Pumps", "CHECK & OFF", "N-7", "Before Starting Engines"),
        item("bse-fuselage-valve", "Fuselage Valve (if installed)", "CLOSE", "N-7", "Before Starting Engines"),
        item("bse-fuel-jettison", "Fuel Jettison", "OFF", "N-7", "Before Starting Engines"),
        item("bse-cvr", "CVR", "TEST", "N-7", "Before Starting Engines"),
        item("bse-drag-chute", "Drag Chute Handle", "STOWED", "N-7", "Before Starting Engines", dragChuteInstalled),
        item("bse-takeoff-data", "Takeoff Data (N1, V1, VR, V2 & T.O. Distance)", "COMPUTE & BUGS SET", "N-7", "Before Starting Engines"),
      ],
    },
    {
      id: "starting-engines",
      title: "Starting Engines",
      sequence: 40,
      sources: source("N-8–N-9", "Starting Engines"),
      items: [
        item("start-cabin-door", "Cabin Door", "SECURED & LIGHT OUT", "N-8", "Starting Engines"),
        item("start-fuel-computers", "Fuel Computers", "ON", "N-8", "Starting Engines"),
        item("start-air-conditioner", "Air Conditioner", "OFF", "N-8", "Starting Engines"),
        item("start-aux-heat", "Aux Heat (if installed)", "OFF", "N-8", "Starting Engines"),
        item("start-batteries", "Batteries", "ON", "N-8", "Starting Engines"),
        item("start-inverters", "Inverters", "ON", "N-8", "Starting Engines"),
        item("start-parking-brake", "Parking Brake (hydraulic pressure req’d)", "SET", "N-8", "Starting Engines"),
        item("start-hyd-pump", "Hyd Pump", "OFF", "N-8", "Starting Engines"),
        item("start-beacon", "Beacon Light", "ON", "N-8", "Starting Engines"),
        item("start-thrust-levers", "Thrust Levers", "CUTOFF", "N-8", "Starting Engines"),
        item("start-engine", "Engine", "START (ENSURE N1 ROTATION)", "N-8", "Starting Engines"),
        item("start-startgen-gpu", "Start-Gen Switch — GPU Assisted Start", "OFF @ IDLE", "N-8", "Starting Engines"),
        item("start-startgen-battery", "Start-Gen Switch — Battery Start", "GEN @ IDLE", "N-8", "Starting Engines"),
        item("start-voltmeter-ammeter", "Voltmeter & Ammeter", "CHECK", "N-8", "Starting Engines"),
        item("start-spoilers", "Spoileron/Spoilers", "CHECK", "N-8", "Starting Engines"),
        item("start-flaps", "Flaps", "20° or 8°", "N-8", "Starting Engines"),
        item("start-hyd-pressure", "Hydraulic Pressure", "CHECK", "N-8", "Starting Engines"),
        item("start-other-engine", "Other Engine", "OPTIONAL START", "N-8", "Starting Engines"),
        item("start-gpu-disconnect", "GPU (if used)", "DISCONNECT", "N-8", "Starting Engines"),
        item("start-startgen", "Start-Gen Switches", "GEN", "N-8", "Starting Engines"),
        item("start-battery-charging", "Battery Charging Bus/Current Limiters", "CHECK", "N-9", "Starting Engines"),
        item("start-starter-disengagement", "Starter Disengagement (if required)", "CHECK", "N-9", "Starting Engines"),
        item("start-voltmeters-ammeters", "Voltmeters & Ammeters", "CHECK", "N-9", "Starting Engines"),
      ],
    },
    {
      id: "before-taxi-two-engine",
      title: "Before Taxi — Two Engine",
      sequence: 50,
      sources: source("N-9", "Before Taxi — Two Engine"),
      items: [
        item("bt2-avionics", "Avionics", "SET", "N-9", "Before Taxi — Two Engine"),
        item("bt2-radar", "Radar", "STBY", "N-9", "Before Taxi — Two Engine"),
        item("bt2-breakers", "Circuit Breakers", "IN", "N-9", "Before Taxi — Two Engine"),
        item("bt2-coffee", "Coffee/Oven (if installed)", "AS DESIRED", "N-9", "Before Taxi — Two Engine"),
        item("bt2-fuel-control-governor", "Fuel Control Governor", "CHECK", "N-9", "Before Taxi — Two Engine"),
        item("bt2-windshield-heat", "Windshield Heat", "PURGE AS REQ’D", "N-9", "Before Taxi — Two Engine"),
        item("bt2-lights", "Lights", "ON, AS REQ’D", "N-9", "Before Taxi — Two Engine"),
        item("bt2-antiskid", "Anti-Skid", "ON, LIGHTS OUT", "N-9", "Before Taxi — Two Engine"),
        item("bt2-pax", "Pax Briefing/Cabin Secured", "COMPLETE", "N-9", "Before Taxi — Two Engine"),
        item("bt2-sign", "No Smoking Fasten Seat Belt Sign", "ON", "N-9", "Before Taxi — Two Engine"),
        item("bt2-parking-brake", "Parking Brake", "RELEASE", "N-9", "Before Taxi — Two Engine"),
      ],
    },
    {
      id: "taxi-before-takeoff-two-engine",
      title: "Taxi and Before Takeoff — Two Engine",
      sequence: 60,
      sources: source("N-9–N-10", "Taxi and Before Takeoff — Two Engine"),
      items: [
        item("tbto2-brakes-steering", "Brakes & Steering", "CHECK", "N-9", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-fuel-panel", "Fuel Panel", "CHECKED & BALANCED", "N-9", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-thrust-reversers", "Thrust Reversers", "CHECK & STOWED", "N-9", "Taxi and Before Takeoff — Two Engine", thrustReverserInstalled),
        item("tbto2-flight-controls", "Flight Controls", "CHECK", "N-9", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-flight-instruments", "Flight Instruments", "CHECK", "N-9", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-takeoff-data", "Takeoff Data (N1, V1, VR, V2 & T.O. Distance)", "REVIEWED & BUGS SET", "N-9", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-engine-instruments", "Engine Instruments", "CHECK", "N-9", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-voltmeters-ammeters", "Voltmeters & Ammeters", "CHECK", "N-9", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-nav", "Nav Equipment", "SET", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-radar", "Radar", "AS REQ’D", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-spoilers", "Spoilers", "RETRACTED, LIGHT OUT", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-flaps", "Flaps", "SET 20° or 8°, CHECK INDICATION", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-trims", "Trims (3)", "SET/PRI/LIGHT OUT", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-pressurization", "Pressurization", "SET", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-cabin-air", "Cabin Air", "ON", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-cabin-temp", "Cabin Temp Controls", "SET", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-antiice", "Anti-Ice Systems", "CHECK & AS REQ’D", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-heated-windshield", "Electrically-Heated Windshield (if installed)", "ON", "N-10", "Taxi and Before Takeoff — Two Engine"),
        item("tbto2-briefing", "Crew Takeoff Briefing", "COMPLETE", "N-10", "Taxi and Before Takeoff — Two Engine"),
      ],
    },
    {
      id: "before-taxi-one-engine",
      title: "Before Taxi — One Engine",
      sequence: 70,
      sources: source("N-10", "Before Taxi — One Engine"),
      items: [
        item("bt1-gpu", "GPU (if used)", "DISCONNECT", "N-10", "Before Taxi — One Engine"),
        item("bt1-startgen", "Start-Gen Switch", "GEN", "N-10", "Before Taxi — One Engine"),
        item("bt1-voltmeter", "Voltmeter & Ammeter", "CHECK", "N-10", "Before Taxi — One Engine"),
        item("bt1-avionics", "Avionics", "SET", "N-10", "Before Taxi — One Engine"),
        item("bt1-radar", "Radar", "STBY", "N-10", "Before Taxi — One Engine"),
        item("bt1-breakers", "Circuit Breakers", "IN", "N-10", "Before Taxi — One Engine"),
        item("bt1-coffee", "Coffee/Oven (if installed)", "AS DESIRED", "N-10", "Before Taxi — One Engine"),
        item("bt1-lights", "Lights", "ON, AS REQ’D", "N-10", "Before Taxi — One Engine"),
        item("bt1-antiskid", "Anti-Skid", "ON, LIGHTS OUT", "N-10", "Before Taxi — One Engine"),
        item("bt1-pax", "Pax Briefing/Cabin Secured", "COMPLETE", "N-10", "Before Taxi — One Engine"),
        item("bt1-sign", "No Smoking Fasten Seat Belt Sign", "ON", "N-10", "Before Taxi — One Engine"),
        item("bt1-parking-brake", "Parking Brake", "RELEASE", "N-10", "Before Taxi — One Engine"),
      ],
    },
    {
      id: "taxi-before-takeoff-one-engine",
      title: "Taxi and Before Takeoff — One Engine",
      sequence: 80,
      sources: source("N-11–N-12", "Taxi and Before Takeoff — One Engine"),
      items: [
        item("tbto1-brakes-steering", "Brakes & Steering", "CHECK", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-fuel-panel", "Fuel Panel", "CHECKED & BALANCED", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-flight-instruments", "Flight Instruments", "CHECK", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-takeoff-data", "Takeoff Data (N1, V1, VR, V2 & T.O. Distance)", "REVIEWED & BUGS SET", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-nav", "Nav Equipment", "SET", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-radar", "Radar", "AS REQ’D", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-spoilers", "Spoilers", "RETRACTED, LIGHT OUT", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-flaps", "Flaps", "SET 20° or 8°, CHECK INDICATION", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-trims", "Trims (3)", "SET/PRI/LIGHT OUT", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-pressurization", "Pressurization", "SET", "N-11", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-air-conditioner", "Air Conditioner", "OFF", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-aux-heat", "Aux Heat (if installed)", "OFF", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-thrust-lever", "Thrust Lever", "CUTOFF", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-second-engine", "Engine", "START", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-startgen", "Start-Gen Switch", "GEN @ IDLE", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-battery-charging", "Battery Charging Bus/Current Limiters", "CHECK", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-starter-disengagement", "Starter Disengagement (if required)", "CHECK", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-voltmeters", "Voltmeter & Ammeters", "CHECK", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-cabin-temp", "Cabin Temp Controls", "SET", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-antiice", "Anti-Ice Systems", "CHECK & AS REQ’D", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-heated-windshield", "Electrically-Heated Windshield (if installed)", "ON", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-engine-instruments", "Engine Instruments", "CHECK", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-thrust-reversers", "Thrust Reversers", "CHECK & STOWED", "N-12", "Taxi and Before Takeoff — One Engine", thrustReverserInstalled),
        item("tbto1-fuel-control-governor", "Fuel Control Governor", "CHECK", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-flight-controls", "Flight Controls", "CHECK", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-fuel-panel-final", "Fuel Panel", "CHECKED & BALANCED", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-cabin-air", "Cabin Air", "ON", "N-12", "Taxi and Before Takeoff — One Engine"),
        item("tbto1-briefing", "Crew Takeoff Briefing", "COMPLETE", "N-12", "Taxi and Before Takeoff — One Engine"),
      ],
    },
    {
      id: "runway-lineup",
      title: "Runway Lineup",
      sequence: 90,
      sources: source("N-12", "Runway Lineup"),
      items: [
        item("lineup-parking-brake", "Parking Brake", "RELEASED", "N-12", "Runway Lineup"),
        item("lineup-transponder", "Transponder", "ON", "N-12", "Runway Lineup"),
        item("lineup-pitot-heat", "Pitot Heat", "ON", "N-12", "Runway Lineup"),
        item("lineup-lights", "Lights (Strobe, Recognition & Landing)", "ON", "N-12", "Runway Lineup"),
        item("lineup-stall-warning", "Stall Warning", "ON", "N-12", "Runway Lineup"),
        item("lineup-ignition", "Ignition", "ON", "N-12", "Runway Lineup"),
        item("lineup-annunciator", "Annunciator Panel", "NORMAL", "N-12", "Runway Lineup"),
      ],
    },
    {
      id: "after-takeoff",
      title: "After Takeoff",
      sequence: 100,
      sources: source("N-13", "After Takeoff"),
      items: [
        item("afterto-gear", "Landing Gear (positive rate)", "UP", "N-13", "After Takeoff"),
        item("afterto-yaw-damper", "Yaw Damper", "ENGAGED", "N-13", "After Takeoff"),
        item("afterto-flaps", "Flaps", "UP", "N-13", "After Takeoff"),
        item("afterto-ignition", "Ignition", "OFF", "N-13", "After Takeoff"),
        item("afterto-pressurization", "Pressurization", "CHECK", "N-13", "After Takeoff"),
        item("afterto-lights", "Landing/Taxi Lights", "OFF", "N-13", "After Takeoff"),
        item("afterto-hyd-pressure", "Hydraulic Pressure", "CHECK", "N-13", "After Takeoff"),
        item("afterto-aoa", "Angle-of-Attack Indicators", "CROSS CHECK", "N-13", "After Takeoff"),
      ],
    },
    {
      id: "climb",
      title: "Climb",
      sequence: 110,
      sources: source("N-13", "Climb"),
      items: [
        item("climb-10000-sign", "10,000 Ft — No Smoking Fasten Seat Belt Sign", "AS REQ’D", "N-13", "Climb"),
        item("climb-10000-pressurization", "10,000 Ft — Pressurization", "CHECKED", "N-13", "Climb"),
        item("climb-transition-altimeters", "18,000 Ft (or Transition Altitude) — Altimeters", "SET 29.92'' Hg (1013 mb)", "N-13", "Climb"),
        item("climb-transition-recognition", "18,000 Ft (or Transition Altitude) — Recognition Light", "OFF", "N-13", "Climb"),
        item("climb-transition-aircon", "18,000 Ft (or Transition Altitude) — Air Conditioner", "OFF, IF APPLICABLE", "N-13", "Climb"),
        item("climb-transition-oxygen", "18,000 Ft (or Transition Altitude) — Oxygen Pressure", "CHECK", "N-13", "Climb"),
        item("climb-transition-emerpress", "18,000 Ft (or Transition Altitude) — EMER PRESS Switches", "NORMAL", "N-13", "Climb"),
        item("climb-fl350-aircon", "FL 350 — Air Conditioner", "OFF", "N-13", "Climb"),
      ],
    },
    {
      id: "cruise",
      title: "Cruise",
      sequence: 120,
      sources: source("N-14", "Cruise"),
      items: [
        item("cruise-pressurization", "Pressurization", "CHECK & NORMAL", "N-14", "Cruise"),
        item("cruise-fuel", "Fuel Management", "AS REQ’D", "N-14", "Cruise"),
        item("cruise-engine-instruments", "Engine Instruments", "CHECK", "N-14", "Cruise"),
        item("cruise-cabin-temp", "Cabin Temp Controls", "SET", "N-14", "Cruise"),
        item("cruise-other-systems", "Other Systems", "MONITOR", "N-14", "Cruise"),
      ],
    },
    {
      id: "descent",
      title: "Descent",
      sequence: 130,
      sources: source("N-14", "Descent"),
      items: [
        item("descent-windshield-heat", "Windshield Heat", "AS REQ’D", "N-14", "Descent"),
        item("descent-aux-defog", "Windshield Aux Defog (if installed)", "AS REQ’D", "N-14", "Descent"),
        item("descent-cabin-controller", "Cabin Controller", "FIELD ELEVATION", "N-14", "Descent"),
        item("descent-antiice", "Anti-Ice Systems", "AS REQ’D", "N-14", "Descent"),
        item("descent-transition-altimeters", "FL 180 (or Transition Level) — Altimeters", "SET BARO & CROSS CHECK", "N-14", "Descent"),
        item("descent-transition-recognition", "FL 180 (or Transition Level) — Recognition Light", "ON", "N-14", "Descent"),
        item("descent-transition-pressurization", "FL 180 (or Transition Level) — Pressurization", "CHECK", "N-14", "Descent"),
        item("descent-transition-sign", "FL 180 (or Transition Level) — No Smoking Fasten Seat Belt Sign", "ON", "N-14", "Descent"),
        item("descent-transition-pax", "FL 180 (or Transition Level) — Pax Briefing/Cabin Secured", "COMPLETE", "N-14", "Descent"),
      ],
    },
    {
      id: "approach",
      title: "Approach",
      sequence: 140,
      sources: source("N-14", "Approach"),
      items: [
        item("approach-breakers", "Circuit Breakers", "IN", "N-14", "Approach"),
        item("approach-pressure", "Hydraulic & Emergency Air Pressure", "CHECK", "N-14", "Approach"),
        item("approach-landing-data", "Landing Data (N1, VREF, VAPP, Distance)", "COMPUTED & SET", "N-14", "Approach"),
        item("approach-fuel", "Fuel", "BALANCED", "N-14", "Approach"),
        item("approach-briefing", "Approach Setup & Briefing", "COMPLETE", "N-14", "Approach"),
      ],
    },
    {
      id: "before-landing",
      title: "Before Landing",
      sequence: 150,
      sources: source("N-16", "Before Landing"),
      items: [
        item("beforeldg-spoilers", "Spoilers", "RETRACTED", "N-16", "Before Landing"),
        item("beforeldg-flaps-initial", "Flaps", "8° or 20°", "N-16", "Before Landing"),
        item("beforeldg-gear", "Landing Gear", "DOWN", "N-16", "Before Landing"),
        item("beforeldg-lights", "Landing/Taxi Lights", "AS REQ’D", "N-16", "Before Landing"),
        item("beforeldg-antiskid", "Anti-Skid", "ON, LIGHTS OUT", "N-16", "Before Landing"),
        item("beforeldg-engine-sync", "Engine Sync", "OFF", "N-16", "Before Landing"),
        item("beforeldg-flaps-final", "Flaps", "DOWN & INDICATED", "N-16", "Before Landing"),
        item("beforeldg-hyd", "Hydraulic Pressure", "CHECK", "N-16", "Before Landing"),
        item("beforeldg-ignition", "Ignition", "ON", "N-16", "Before Landing"),
        item("beforeldg-autopilot", "Autopilot", "DISENGAGE", "N-16", "Before Landing"),
      ],
    },
    {
      id: "go-around",
      title: "Go Around",
      sequence: 160,
      sources: source("N-16", "Go Around"),
      items: [
        item("ga-autopilot", "Autopilot", "DISENGAGED", "N-16", "Go Around"),
        item("ga-thrust", "Thrust Levers", "AS REQ’D", "N-16", "Go Around"),
        item("ga-spoilers", "Spoilers", "RETRACTED", "N-16", "Go Around"),
        item("ga-flaps", "Flaps", "20°", "N-16", "Go Around"),
        item("ga-gear", "Landing Gear (positive rate)", "UP", "N-16", "Go Around"),
        item("ga-approach-climb", "Climb", "AT APPROACH CLIMB SPEED", "N-16", "Go Around"),
        item("ga-clear-obstacles", "Clear of Obstacles", "VREF + 30, FLAPS UP", "N-16", "Go Around"),
      ],
    },
    {
      id: "after-landing",
      title: "After Landing / Clearing Runway",
      sequence: 170,
      sources: source("N-17", "After Landing / Clearing Runway"),
      items: [
        item("afterldg-stall-warning", "Stall Warning", "OFF", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-ignition", "Ignition", "OFF", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-cabin-air", "Cabin Air", "OFF", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-pitot-alcohol", "Pitot Heat & Alcohol", "OFF", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-heat", "Defog, Windshield, Nacelle, Stab & Wing Heat", "AS REQ’D", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-lights", "Lights", "AS DESIRED", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-one-thrust", "One Thrust Lever (Optional)", "CUTOFF", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-spoilers", "Spoilers", "RETRACT", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-flaps", "Flaps", "UP", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-hyd", "Hydraulic Pressure", "CHECK", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-avionics", "Unnecessary Avionics", "OFF", "N-17", "After Landing / Clearing Runway"),
        item("afterldg-transponder", "Transponder", "STBY or OFF", "N-17", "After Landing / Clearing Runway"),
      ],
    },
    {
      id: "shutdown",
      title: "Shutdown",
      sequence: 180,
      sources: source("N-17–N-18", "Shutdown"),
      items: [
        item("shutdown-brake-chocks", "Parking Brake/Chocks", "SET", "N-17", "Shutdown"),
        item("shutdown-antiice", "Anti-Ice Systems", "OFF", "N-17", "Shutdown"),
        item("shutdown-emergency-lights", "Emergency Lights (if installed)", "DISARM", "N-17", "Shutdown"),
        item("shutdown-avionics", "Avionics", "OFF", "N-17", "Shutdown"),
        item("shutdown-standby-gyro", "Standby Attitude Gyro", "CAGE", "N-17", "Shutdown"),
        item("shutdown-emergency-battery", "Emergency Battery(ies)", "OFF", "N-17", "Shutdown"),
        item("shutdown-coffee", "Coffee/Oven (if installed)", "OFF", "N-17", "Shutdown"),
        item("shutdown-thrust-levers", "Thrust Levers", "CUTOFF", "N-18", "Shutdown"),
        item("shutdown-startgen", "Start-Gen Switches", "OFF", "N-18", "Shutdown"),
        item("shutdown-inverters", "Inverters", "OFF", "N-18", "Shutdown"),
        item("shutdown-fuel-transfer", "Fuel Transfer", "OFF", "N-18", "Shutdown"),
        item("shutdown-crossflow", "Crossflow Valve", "CLOSED", "N-18", "Shutdown"),
        item("shutdown-beacon", "Beacon Light", "OFF", "N-18", "Shutdown"),
        item("shutdown-batteries", "Batteries", "OFF", "N-18", "Shutdown"),
        item("shutdown-controls-lock", "Controls Lock", "INSTALL", "N-18", "Shutdown"),
      ],
    },
    {
      id: "quick-turnaround",
      title: "Quick Turnaround — One or No Engine Shutdown",
      sequence: 190,
      sources: source("N-18", "Quick Turnaround"),
      items: [
        item("quick-cabin-door", "Cabin Door", "SECURED", "N-18", "Quick Turnaround"),
        item("quick-air-conditioner", "Air Conditioner", "OFF", "N-18", "Quick Turnaround"),
        item("quick-aux-heat", "Aux Heat (if installed)", "OFF", "N-18", "Quick Turnaround"),
        item("quick-engine", "Engine", "START (ENSURE N1 ROTATION) (2 RUNNING)", "N-18", "Quick Turnaround"),
        item("quick-startgen", "Start-Gen Switches", "GEN", "N-18", "Quick Turnaround"),
        item("quick-voltmeters", "Voltmeter & Ammeters", "CHECK", "N-18", "Quick Turnaround"),
        item("quick-battery-charging", "Battery Charging Bus/Current Limiters (if required)", "CHECK", "N-18", "Quick Turnaround"),
        item("quick-starter", "Starter Disengagement (if required)", "CHECK", "N-18", "Quick Turnaround"),
        item("quick-breakers", "Circuit Breakers", "IN", "N-18", "Quick Turnaround"),
        item("quick-avionics", "Avionics", "SET", "N-18", "Quick Turnaround"),
        item("quick-coffee", "Coffee/Oven (if installed)", "AS DESIRED", "N-18", "Quick Turnaround"),
        item("quick-antiice", "Anti-Ice Systems", "AS REQ’D", "N-18", "Quick Turnaround"),
        item("quick-pax", "Pax Briefing/Cabin Secured", "COMPLETE", "N-18", "Quick Turnaround"),
        item("quick-sign", "No Smoking Fasten Seat Belt Sign", "ON", "N-18", "Quick Turnaround"),
      ],
    },
  ],
};
